;; #source  
;;; generated by Ott 0.28 from: ./ott/lang_simple.ott

#lang racket
(require redex/reduction-semantics)

;; #source file ./ott/lang_simple.ott  lines 4 - 6 
;; #source file ./ott/lang_simple.ott  lines 8 - 33 

;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; Redex model for GDTL
;; Accompanying "Approximate Normalization for Gradual Dependnently Typed Languages"
;; (mostly) auto-generated from an Ott definition
;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(provide (all-defined-out))

(define currently-defined-vars 
  (make-hasheq))

;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; Syntax Definition
;; gt gT : gradual terms, the source language
;; gu gU : gradual canonical forms
;; et eT : evidence terms, used to define dynamic semantics, are result of elaboration
;; ep : the evidence ascribed to terms. Is a wrapper around a canonical type
;; ev eV : evidence values: well-formed evidence terms that cannot be reduced
;; rv rV : raw values: evidence values forbidding ascription with evidence at the top level
;;;;;;;;;;;;;;;;;;;;;;;;;;;;

;; #source file ./ott/lang_simple.ott  lines 35 - 111 
;; #source file ./ott/lang_simple.ott  lines 116 - 118 
;; #source file ./ott/lang_simple.ott  lines 121 - 121 
;; #source file ./ott/lang_simple.ott  lines 127 - 135 and file ./ott/lang_simple.ott  lines 140 - 152 and file ./ott/lang_simple.ott  lines 156 - 190 and file ./ott/lang_simple.ott  lines 195 - 204 and file ./ott/lang_simple.ott  lines 213 - 218 and file ./ott/lang_simple.ott  lines 221 - 226 and file ./ott/lang_simple.ott  lines 228 - 230 and file ./ott/lang_simple.ott  lines 233 - 243 and file ./ott/lang_simple.ott  lines 246 - 248 and file ./ott/lang_simple.ott  lines 250 - 279 and file ./ott/lang_simple.ott  lines 284 - 298 and file ./ott/lang_simple.ott  lines 303 - 311 and file ./ott/lang_simple.ott  lines 314 - 315 and file ./ott/lang_simple.ott  lines 317 - 320 and file ./ott/lang_simple.ott  lines 322 - 326 and file ./ott/lang_simple.ott  lines 334 - 336 and file ./ott/lang_simple.ott  lines 345 - 360 and file ./ott/lang_simple.ott  lines 364 - 373 and file ./ott/lang_simple.ott  lines 376 - 381 and file ./ott/lang_simple.ott  lines 383 - 394 and file ./ott/lang_simple.ott  lines 398 - 400 and file ./ott/lang_simple.ott  lines 411 - 416 and file ./ott/lang_simple.ott  lines 418 - 424 and file ./ott/lang_simple.ott  lines 470 - 473 and file ./ott/lang_simple.ott  lines 475 - 479 and file ./ott/lang_simple.ott  lines 481 - 485 and file ./ott/lang_simple.ott  lines 612 - 617 and file ./ott/lang_simple.ott  lines 620 - 622 and file ./ott/lang_simple.ott  lines 624 - 626 and file ./ott/lang_simple.ott  lines 628 - 629 
(define-language L  

(level i j ::= natural)

;; #source file ./ott/lang_simple.ott  lines 284 - 298 
  (canonical gu gU ::= 
    (CanonicalLam var gu)
    (CanonicalAtomic grr)
    CanonicalDyn
    (CanonicalPi var gU_11 gU_22))
  ;grammar_pp, 2817: and 
;; #source file ./ott/lang_simple.ott  lines 303 - 311 
  (atomic grr gRR ::= 
    (AtomicSpine var ge)
    (AtomicSet i)
    AtomicNat
    AtomicZero
    (AtomicSucc gu))
  ;grammar_pp, 2817: and 
;; #source file ./ott/lang_simple.ott  lines 322 - 326 
  (spine ge ::= 
    SpineEmpty
    (SpineCons ge gu)
    (SpineNatElim ge gU gu_11 var var gu_22))

;; #source file ./ott/lang_simple.ott  lines 334 - 336 
  (epsilon ep ::= 
    (EvidenceEv gU))

;; #source file ./ott/lang_simple.ott  lines 156 - 190 
  (term tt ett TT ::= 
    (TermLam var tt)
    (TermApp tt_11 tt_22)
    var
    (TermSet i)
    (TermPi var TT_11 TT_22)
    (TermAnn tt TT)
    (TermEp ep tt)
    TermDyn
    TermError
    TermNat
    TermZero
    (TermSucc tt)
    (TermNatElim tt_11 TT tt_22 var var tt_33))

;; #source file ./ott/lang_simple.ott  lines 481 - 485 
  (Env ::= 
    EnvEmpty
    (EnvExt var gU Env)
    (Envconcat Env_11 Env_22))

(iinf ::= number)

;; #source file ./ott/lang_simple.ott  lines 398 - 400 
  (dummyev dummyeV ::= 
    (DummyEvidenceValueEv ep rv)
    (DummyEvidenceValueRaw rv))

;; #source file ./ott/lang_simple.ott  lines 628 - 629 
  (ent ::= 
    (ENTTriple et gu gU))

;; #source file ./ott/lang_simple.ott  lines 624 - 626 
  (iinfs jinfs ::= 
    (UniverseMultiSetSingleton iinf)
    (UniverseMultiSetSum iinfs jinfs))

;; #source file ./ott/lang_simple.ott  lines 620 - 622 
  (is js ::= 
    (LevelMultiSetSingleton i)
    (LevelMultiSetSum is js))

;; #source file ./ott/lang_simple.ott  lines 418 - 424 
  (evalContext EC ::= 
    (TermApp hole et)
    (TermApp ev hole)
    (TermPi x hole eT)
    (TermEp ep hole))

;; #source file ./ott/lang_simple.ott  lines 411 - 416 
  (simpleContext SC ::= 
    (TermApp hole t)
    (TermApp sv hole)
    (TermPi x hole T)
    (TermAnn hole T))

;; #source file ./ott/lang_simple.ott  lines 345 - 360 
  (et eT ::= 
    (TermLam var et)
    (TermApp et_11 et_22)
    var
    (TermPi var eT_11 eT_22)
    (TermSet i)
    TermDyn
    (TermEp ep et)
    TermNat
    TermZero
    (TermSucc et)
    (TermNatElim et_11 eT et_22 var var et_33)
    TermError)

;; #source file ./ott/lang_simple.ott  lines 213 - 218 
  (u U ::= 
    (CanonicalLam var u)
    (CanonicalAtomic rr)
    (CanonicalPi var U_11 U_22))

;; #source file ./ott/lang_simple.ott  lines 246 - 248 
  (gtCheckOnly gTCheckOnly ::= 
    (TermLam var gt)
    (TermPi var gT_11 gT_22))

;; #source file ./ott/lang_simple.ott  lines 383 - 394 
  (ev eV ::= 
    (TermEp ep rv)
    (TermPi var eV eT)
    (TermLam var et)
    (TermSet i)
    TermDyn
    TermNat
    TermZero
    (TermSucc ev))

;; #source file ./ott/lang_simple.ott  lines 317 - 320 
  (grrNoSub ::= 
    (AtomicSet i)
    AtomicNat
    AtomicZero)

;; #source file ./ott/lang_simple.ott  lines 314 - 315 
  (guNoSub ::= 
    (CanonicalAtomic grrNoSub))

;; #source file ./ott/lang_simple.ott  lines 228 - 230 
  (e ::= 
    SpineEmpty
    (SpineCons e u))

;; #source file ./ott/lang_simple.ott  lines 140 - 152 
  (ttSynth ettSynth TTSynth ::= 
    (TermApp tt_11 tt_22)
    var
    (TermSet i)
    (TermAnn gt gT)
    TermDyn
    (TermEp ep et)
    TermNat
    TermZero
    (TermSucc tt)
    (TermNatElim tt_11 TT tt_22 var var tt_33))

;; #source file ./ott/lang_simple.ott  lines 364 - 373 
  (rv rV ::= 
    (TermLam var et)
    (TermPi var eV eT)
    (TermSet i)
    TermDyn
    TermNat
    TermZero
    (TermSucc ev))

;; #source file ./ott/lang_simple.ott  lines 470 - 473 
  (SGamma ::= 
    EnvEmpty
    (EnvExt var U SGamma)
    (Envconcat SGamma_11 SGamma_22))

;; #source file ./ott/lang_simple.ott  lines 475 - 479 
  (Gamma ::= 
    EnvEmpty
    (EnvExt var gU Gamma)
    (Envconcat Gamma_11 Gamma_22))

;; #source file ./ott/lang_simple.ott  lines 195 - 204 
  (t T ::= 
    (TermLam var t)
    (TermApp t_11 t_22)
    var
    (TermPi var T_11 T_22)
    (TermSet i)
    (TermAnn t T))

;; #source file ./ott/lang_simple.ott  lines 233 - 243 
  (gtSynth gTSynth ::= 
    (TermApp gt_11 gt_22)
    var
    (TermSet i)
    (TermAnn gt gT)
    TermDyn
    TermNat
    TermZero
    (TermSucc gt)
    (TermNatElim gt_11 gT gt_22 var var gt_33))

;; #source file ./ott/lang_simple.ott  lines 250 - 279 
  (gt gT ::= 
    (TermLam var gt)
    (TermApp gt_11 gt_22)
    var
    (TermSet i)
    (TermPi var gT_11 gT_22)
    (TermAnn gt gT)
    TermDyn
    TermNat
    TermZero
    (TermSucc gt)
    (TermNatElim gt_11 gT gt_22 var var gt_33))

;; #source file ./ott/lang_simple.ott  lines 221 - 226 
  (rr RR ::= 
    (AtomicSpine var e)
    (AtomicSet i))

;; #source file ./ott/lang_simple.ott  lines 376 - 381 
  (simpleValue sv sV ::= 
    (TermLam var t)
    (TermPi var sV T)
    (TermSet i))
   (var x y z X Y Z ::= variable-not-otherwise-mentioned)

    #:binding-forms

    (TermLam x tt #:refers-to (shadow x))
    (TermPi x TT_11 TT_22 #:refers-to (shadow x))
    (StaticTermLam x t #:refers-to (shadow x))
    (StaticTermPi x T_11 T_22)
    (SCanonicalLam x u #:refers-to (shadow x))

    (GradualTermCheckOnlyLam x gt #:refers-to (shadow x))
    (GradualTermCheckOnlyPi x gT_11 gT_22 #:refers-to (shadow x))
    (GradualTermLam x gt #:refers-to (shadow x))
    (GradualTermPi x gT_11 gT_22 #:refers-to (shadow x))
    (CanonicalLam x gu #:refers-to (shadow x))
    (CanonicalPi x gU_11 gU_22 #:refers-to (shadow x))

    (EvidenceTermLam x et #:refers-to (shadow x))
    (EvidenceTermPi x eT_11 eT_22 #:refers-to (shadow x))
    (RawValueLam x et #:refers-to (shadow x))
    (SimpleValueLam x t #:refers-to (shadow x))
    (SimpleValuePi x sV T #:refers-to (shadow x))
    (EvidenceValuePi x eV eT #:refers-to (shadow x))
    (EvidenceValueLam x et #:refers-to (shadow x))

)

;;;; subrules 
;; #source file ./ott/lang_simple.ott  lines 643 - 643 and file ./ott/lang_simple.ott  lines 644 - 644 and file ./ott/lang_simple.ott  lines 647 - 647 and file ./ott/lang_simple.ott  lines 648 - 648 and file ./ott/lang_simple.ott  lines 649 - 649 and file ./ott/lang_simple.ott  lines 650 - 650 and file ./ott/lang_simple.ott  lines 651 - 651 and file ./ott/lang_simple.ott  lines 652 - 652 and file ./ott/lang_simple.ott  lines 653 - 653 and file ./ott/lang_simple.ott  lines 654 - 654 and file ./ott/lang_simple.ott  lines 655 - 655 and file ./ott/lang_simple.ott  lines 656 - 656 and file ./ott/lang_simple.ott  lines 658 - 658 and file ./ott/lang_simple.ott  lines 659 - 659 and file ./ott/lang_simple.ott  lines 664 - 664 and file ./ott/lang_simple.ott  lines 665 - 665 and file ./ott/lang_simple.ott  lines 666 - 666 and file ./ott/lang_simple.ott  lines 669 - 669 
;; #source file ./ott/lang_simple.ott  lines 680 - 691 
;; #source file ./ott/lang_simple.ott  lines 693 - 962 

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; Hand-written implementations
;; These are mostly to speed up type-checking and running GDTL programs
;; They should match the inductive definitions in the ott file
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

;; The (precision) meet of two types/terms
;; Throws an exception if the meet does not exist

(define (meet gu_1 gu_2)
  (with-handlers ([exn:fail:redex? (lambda (exn) (error 'RuntimeError "Incompatible types:\n    ~a\nand\n   ~a" (pt gu_1) (pt gu_2) ))])
    (meet_ (term (^ ,gu_1 ,gu_2)))
  ))

(define meet_
  (term-match/single L
               [(^ CanonicalDyn gu) (term gu)]
               [(^ gu CanonicalDyn) (term gu)]
               [(^ guNoSub guNoSub) (term guNoSub)]
               [(^ (CanonicalAtomic (AtomicSucc gu)) (CanonicalAtomic (AtomicSucc gu_2))) (term (CanonicalAtomic (AtomicSucc ,(meet (term gu) (term gu_2) )))) ]
               [(^ (CanonicalAtomic (AtomicSpine x SpineEmpty)) (CanonicalAtomic (AtomicSpine x SpineEmpty))) (term (CanonicalAtomic (AtomicSpine x SpineEmpty)))]
               [(^ (CanonicalAtomic (AtomicSpine x (SpineCons ge_1 gu_1))) (CanonicalAtomic (AtomicSpine x (SpineCons ge_2 gu_2))))
                (term-let ([(CanonicalAtomic (AtomicSpine x ge_3)) (meet (term (CanonicalAtomic (AtomicSpine x ge_1))) (term (CanonicalAtomic (AtomicSpine x ge_2))))])
                          (term (CanonicalAtomic (AtomicSpine x (SpineCons ge_3 ,(meet (term gu_1) (term gu_2)))))))]
               [(^ (CanonicalAtomic (AtomicSpine x (SpineNatElim ge_ gU_ gu_2 x_1 x_2 gu_3))) (CanonicalAtomic (AtomicSpine x (SpineNatElim ge_^ gU_^ gu_2^ x_1^ x_2^ gu_3^))))
                (term-let ([(CanonicalAtomic (AtomicSpine x ge_3)) (meet (term (CanonicalAtomic (AtomicSpine x ge_))) (term (CanonicalAtomic (AtomicSpine x ge_^))))])
                          (term (CanonicalAtomic (AtomicSpine x (SpineNatElim ge_3 ,(meet (term gU_) (term gU_^)) ,(meet (term gu_2) (term gu_2^)) ,(meet (term x_1) (term x_1^)) ,(meet (term x_2) (term x_2^)) ,(meet (term gu_3) (term gu_3^)) )))))]
               ;;;;TODO alpha rename
               [(^ (CanonicalLam x gu_1) (CanonicalLam y gu_2))
                (let ([z (gensym)])
                 (term (CanonicalLam ,z ,(meet (term (substitute gu_1 x ,z)) (term (substitute gu_2 y ,z))) )))]
               [(^ (CanonicalPi x gU_11 gU_12) (CanonicalPi y gU_21 gU_22))
                (let ([z (gensym)])
                 (term (CanonicalPi ,z ,(meet (term gU_11) (term gU_21)) ,(meet (term (substitute gU_12 x ,z)) (term (substitute gU_22 y ,z))) )))]
               ))

;;Find the eta-expanded form of gu at type gU
(define (eta-expand gu gU)
  (first (judgment-holds (GEtaExpandC ,gu gu_ret ,gU) gu_ret)
))

(define (hsub x_old gu_new gU gu) ((hsub_ gu) x_old gu_new gU) )

(define hsub_
  (term-match/single L
                     [CanonicalDyn (lambda (x_old gu_new gU) (term CanonicalDyn))]
                     [(CanonicalLam x gu) (lambda (x_old gu_new gU)
                                            (term (CanonicalLam x ,(hsub x_old gu_new gU (term gu)) )))]
                     [(CanonicalPi x gU_1 gU_2)
                      (lambda (x_old gu_new gU)
                        (term (CanonicalPi x
                                         ,(hsub x_old gu_new gU (term gU_1)) 
                                         ,(hsub x_old gu_new gU (term gU_2)))))]
                     [guNoSub (lambda (x_old gu_new gU)
                                                        (term guNoSub))]
                     [(CanonicalAtomic (AtomicSucc gu)) (lambda (x_old gu_new gU) (term (CanonicalAtomic (AtomicSucc ,(hsub x_old gu_new gU (term gu))))))]
                     [(CanonicalAtomic (AtomicSpine x ge))
                      (lambda (x_old gu_new gU) (if (equal? (term x) x_old)
                                                    (term-let ([(TermPair gu_ret1 gU_ret2) ((hsub-spine (term ge)) x_old gu_new gU)])
                                                               (term gu_ret1)
                                                               )
                                                               (term (CanonicalAtomic (AtomicSpine x ,((hsub-map-spine (term ge)) x_old gu_new gU)) ))))]
                     )
  )

;; Helpers for hsub

;;Perform a substitution in each element of a spine
(define hsub-map-spine
  (term-match/single L
                     [SpineEmpty (lambda (x_old gu_new gU) (term SpineEmpty))]
                     [(SpineCons ge gu) (lambda (x_old gu_new gU)
                                          (term (SpineCons ,((hsub-map-spine (term ge)) x_old gu_new gU) ,(hsub x_old gu_new gU (term gu)))))]
                     [(SpineNatElim ge gU_motive gu_2 x_1 x_2 gu_3) (lambda (x_old gu_new gU)
                                          (term (SpineNatElim ,((hsub-map-spine (term ge)) x_old gu_new gU)
                                                              ,(hsub x_old gu_new gU (term gU_motive))
                                                              ,(hsub x_old gu_new gU (term gu_2))
                                                              x_1
                                                              x_2
                                                              ,(hsub x_old gu_new gU (term gu_3)))))]))

;; Perform a hereditary substitution on a spine whose head is the variable being replaced
(define hsub-spine
  (term-match/single L
                     [SpineEmpty (lambda (x gu_new gU) (term (TermPair ,gu_new ,gU)))]
                     [(SpineCons ge gu) (lambda (x gu_new gU) (hsub-spine-withsub (term (TermPair ,(hsub x gu_new gU (term gu)) ,( (hsub-spine (term ge)) x gu_new gU) )) )) ]
                     [(SpineNatElim ge gU_motive gu_Z x_n x_rec gu_S) (lambda (x gu_new gU)
                                                                       (let ([subbed (hsub x gu_new gU (term (CanonicalAtomic (AtomicSpine x ge))))])
                                                                        (term (TermPair
                                                                         ,(hsub-natElim (term (NatElim ,subbed gU_motive gu_Z x_n x_rec gu_S )) )
                                                                         ,(bodysub (term CNat) subbed (term gU_motive))
                                                                         )))
                                                                        
                                                                        ) ]))

;; Perform a hereditary subtitution on a cons-spine whose head is the variable being replaced,
;; Given the result of substituting on all but the last element of the spine
(define hsub-spine-withsub
  (term-match/single L
                     [(TermPair gu_subbed (TermPair (CanonicalLam x gu_body) (CanonicalPi y gU_dom gU_cod) ))
                      (let ([gu_val (hsub (term x) (term gu_subbed) (term gU_dom) (term gu_body))]
                            [gU_type (hsub (term y) (term gu_subbed) (term gU_dom) (term gU_cod))])
                       (term (TermPair ,(eta-expand gu_val gU_type) ,gU_type )))]
                     [(TermPair gu_subbed (TermPair gu_spine CanonicalDyn)) (term (TermPair CanonicalDyn CanonicalDyn))]
                     [(TermPair gu_subbed (TermPair CanonicalDyn (CanonicalPi y gU_dom gU_cod)) ) (term (TermPair CanonicalDyn ,(hsub (term y) (term gu_subbed) (term gU_dom) (term gU_cod))))]))

(define-term CNat (CanonicalAtomic AtomicNat))

(define hsub-natElim
  (term-match/single L
                     [(NatElim (CanonicalAtomic (AtomicSpine x ge)) gU_motive gu_Z x_n x_rec gu_S )
                      (term (CanonicalAtomic (AtomicSpine x (SpineNatElim ge gU_motive gu_Z x_n x_rec gu_S))))]
                     [(NatElim (CanonicalAtomic (AtomicZero))  )
                      (term gu_Z)]
                     [(NatElim (CanonicalAtomic (AtomicSucc gu)) gU_motive gu_Z x_n x_rec gu_S )
                      (term (hsub x_rec (bodysub CNat gu gU_motive) (hsub-natElim (term (NatElim gu gU_motive gu_Z x_n x_rec gu_S) )) (hsub x_n CNat gu gu_S)   ))]
                     [(NatElim CanonicalDyn gU_motive gu_Z x_n x_rec gu_S )
                      (term CanonicalDyn)]))

(define bodysub_
  (term-match/single L
   [(CanonicalLam x gu) (lambda (gU gu_arg) (hsub (term x) gU gu_arg (term gu) ))]
   [CanonicalDyn (term CanonicalDyn)]
   ))

(define (bodysub gU gu_arg gu_fun)
  ((bodysub_ gu_fun) gU gu_arg))

;; A performance hack
;; We leave all definitions as variables in elaborated form
;; And insert them immediately before evaluating
;; This prevents us from having to re-typecheck definitions
(define perform-elab-substs
  (term-match/single L 
                     [x (if (hash-has-key? currently-defined-vars (term x) ) 
                            (redex-let L ([ (ENTTriple et gu gU) (hash-ref currently-defined-vars (term x)) ]) (term et)  )
                            (term x) )]
                     [(TermLam x et) (term (TermLam x ,(perform-elab-substs (term et)))) ]
                     [(TermApp et_11 et_22) (term (TermApp ,(perform-elab-substs (term et_11)) ,(perform-elab-substs (term et_22))))]
                     [(TermPi x eT_11 eT_22) (term (TermPi x ,(perform-elab-substs (term eT_11)) ,(perform-elab-substs (term eT_22))))]
                     [(TermSet i) (term (TermSet i))]
                     [TermDyn (term TermDyn)]
                     [(TermEp ep et) (term (TermEp ep ,(perform-elab-substs (term et))))]
                     [TermError (term TermError)]
                     ))

;; Compute the domain of a function type or ?
(define dom
  (term-match/single L
                     [CanonicalDyn (term CanonicalDyn)]
                     [(CanonicalPi x gU gU_2) (term gU)]
                     [_ (error "Cannot treat as a function type")]))

;; Helpers for manipulating universe levels
(define-metafunction L 
  succ : i -> i
  [(succ i) ,(+ (term i) 1)])
  
  (define-metafunction L 
  pred : i -> i
  [(pred i) ,(- (term i) 1)])

;;;;;;;;;;;;;;;;;;;;;;;;;
;; Computes replacing of x_old by et_new in et, where et_new has normal form gu at type gU
;; Substitution on evidence terms
;; Because evidence terms contain evidence, when performing a substitution
;; We may also need to subsitute in the evidence
;; Since this is (type-directed) hereditary substitution on normal forms,
;; We need to know the type and normal form of the value we're inserting
;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define-metafunction L 
  esubst : et var et gu gU -> et 
  [(esubst x_old x_old et_new gu gU) et_new ]
  [(esubst y x_old et_new gu gU) y (side-condition (not (equal? (term x_old) (term y)))) ]
  [(esubst (TermPi y eT_1 eT_2) x_old et_new gu gU) 
    (TermPi y (esubst eT_1 x_old et_new gu gU) (esubst eT_2 x_old et_new gu gU ))
    (side-condition (not (equal? (term x_old) (term y))))
  ]
  [(esubst (TermLam y et) x_old et_new gu gU) 
    (TermLam y (esubst et x_old et_new gu gU ))
    (side-condition (not (equal? (term x_old) (term y))))]
  [(esubst (TermApp et_1 et_2) x_old et_new gu gU) (TermApp (esubst et_1 x_old et_new gu gU) (esubst et_2 x_old et_new gu gU))]
  [(esubst (TermEp (EvidenceEv gU_1 ) et) x_old et_new gu gU) (TermEp (EvidenceEv gU_new) (esubst et x_old et_new gu gU))
    (judgment-holds (GHsub  x_old gU gu gU_1 gU_new))]
  [(esubst (TermSet i) x_old et_new gu gU) (TermSet i) ]
  [(esubst TermDyn x_old et_new gu gU) TermDyn]
)

;; Test whether a term can possibly synthesize a type
(define-metafunction L 
 is-check-only : term -> boolean
 [(is-check-only TermDyn) #t]
 [(is-check-only (TermPi x TT_1 TT_2)) #t]
 [(is-check-only (TermLam x tt)) #t]
 [(is-check-only tt) #f] 
)

;;;;;;;;;;;;;;;;;;;
;; Checks whether the input types areof the form (Set i) (Set j)
;; where i < j
;; We need this because Set i and Set j are not *consistent*, we can only convert between them in one direction
;; So when we switch between synthesis and checking, we need to tell whether we're checking the types for Consistency
;; Or checking if we can raise from a lower universe to a higher one
;;;;;;;;;;;;;;;;;;

(define-metafunction L 
 is-set-pair : gU gU_V -> boolean
 [(is-set-pair (CanonicalAtomic (AtomicSet i)) (CanonicalAtomic (AtomicSet j))) #t (side-condition (< (term i) (term j)))]
 [(is-set-pair gU gU_V) #f] 
)

;; Get the typed wrapped in evidence
(define-metafunction L 
 type-in-ev : ep -> gU
 [(type-in-ev (EvidenceEv gU)) gU]
)

;; Pretty-print a term
(define (pt tm)
  (with-handlers ([exn:fail:redex?
                   (lambda (exn) (format "~a" tm))])
    (pretty-term tm)
    ))

;; Pattern-matcher for pretty-printing terms 
(define pretty-term
    (term-match/single L
    [x (symbol->string (term x))]
    [(TermLam x tt) (string-append "(λ " (pt (term x)) " . " (pt (term tt)) ")")]
    [(TermPi x TT_1 TT_2) (string-append "(( " (pt (term x)) " : " (pt (term TT_1)) ") -> " (pt (term TT_2)) ")")]
    [(TermSet i) (string-append "Set" (number->string (term i)))]
    [(TermApp tt_1 tt_2) (string-append "(" (pt (term tt_1)) " " (pt (term tt_2)) ")")]
    [TermDyn "?"]
    [TermError "⊥"]
    [(TermAnn tt_1 tt_2) (string-append (pt (term tt_1)) " :: " (pt (term tt_2)))]
    [(TermDynAnn gU) (string-append "?" (pt (term gU)))]
    [(TermEp (EvidenceEv Gamma gU ) tt) (string-append "〈" (pt (term gU)) "〉" (pt (term tt)))]
    [(CanonicalAtomic grr) (pt (term grr))]
    [(CanonicalLam x gu) (string-append "(λ " (pt (term x)) " . " (pt (term gu)) ")")]
    [(CanonicalPi x gU gU_V) (string-append "(( " (pt (term x)) " : " (pt (term gU)) ") -> " (pt (term gU_V)) ")")]
    [(AtomicSet i) (string-append "Set" (number->string (term i)))]
    [CanonicalDyn "?"]
    [(AtomicSpine x ge) (string-append "(" (pt (term x)) " " (pt (term ge)) ")")]
    [SpineEmpty ""]
    [(SpineCons ge gu) (string-append (pt (term ge)) " " (pt (term gu)))]
    
    ))

;; Print the type wrapped in evidence
(define (printEvType ep)
 (term-let ([(EvidenceEv gU ) ep]) (pt (term gU))))

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; Ott's notion of context doesn't play nice with Redex
;; So we extend our language with our own notion of evaluation contexts
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define-extended-language LContext
  L
  (redexContext RC ::= 
    hole
    (TermApp RC et)
    (TermApp ev RC)
    (TermPi x RC eT)
    (TermEp ep RC))
)

;;;;;;;;;;;;;;;;
;; The contextual-closure of our single-small-step reduction relation
;;;;;;;;;;;;;;;
(define Red
  (reduction-relation LContext
  (--> et_1 et_2 (judgment-holds (Step et_1 et_2)))
  )
)

 

;; #source file ./ott/lang_simple.ott  lines 964 - 966 


;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; Environment helpers, implemented by hand for speed
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

;; Returns the type for x in environment Gamma, or #f if x is not in Gamma
(define (gVarLook x Gamma)
  ((gVarLook_ Gamma) x)
  )

(define gVarLook_
  (term-match/single L 
                     [EnvEmpty (lambda (x) #f)]
                     [(EnvExt y gU Gamma) (lambda (x) (if (equal? x (term y))
                                                          (term gU)
                                                          (gVarLook x (term Gamma)) 
                                                          ))]
                     ))

;; Returns whether x is free in Gamma 
(define (gVarFree x Gamma)
  ((gVarFree Gamma) x)
  )

(define gVarFree_
  (term-match/single L 
                     [EnvEmpty #t]
                     [(EnvExt y gU Gamma) (lambda (x) (if (equal? x (term y))
                                                          #f
                                                          (gVarFree x (term Gamma)) 
                                                          ))]))
;;Judgment-form versions of the above functions

(define-judgment-form
  L
  #:mode (GVarLook I O I)
  #:contract (GVarLook x gU Gamma)

  [
   (where gU ,(gVarLook (term x) (term Gamma)))
   ------------------------------------- "GVarLookHead"
   (GVarLook x gU Gamma)]

  )
(define-judgment-form L 
 
  #:mode (GVarFree I I)
  #:contract (GVarFree x Gamma)

  ;; #source file ./ott/lang_simple.ott  lines 895 - 899 
  [
   (side-condition ,(gVarFree (term x) (term Gamma)))
   ---------------------------------- "GFreeLookCons"
   (GVarFree x Gamma)]
  )

;; #source file ./ott/lang_simple.ott  lines 1135 - 1137 

  

  ;;;;;;;;;;;;;;;;;;;;;;;;;
  ;; Hereditary substitution on environments
  ;;;;;;;;;;;;;;;;;;;;;;;;;

;;; definitions 

(define-judgment-form
  L
  #:mode (GradualEnvSub I I I I O)
  #:contract (GradualEnvSub x gU gu Gamma Gamma_^)

;; #source file ./ott/lang_simple.ott  lines 1497 - 1499 
 [------------------------------------------- "GradualEnvSubEmpty"
  (GradualEnvSub x gU gu EnvEmpty EnvEmpty)]

;; #source file ./ott/lang_simple.ott  lines 1500 - 1505 
 [
  
   (side-condition ,(not (alpha-equivalent? L (term  (CanonicalAtomic  (AtomicSpine  x  SpineEmpty) ) ) (term  (CanonicalAtomic  (AtomicSpine  y  SpineEmpty) ) )))) 
  (GHsub x gU gu gU_11 gU_22)
  (GradualEnvSub x gU gu Gamma Gamma_^)
  ------------------------------------------------------------------------- "GradualEnvSubVarDiff"
  (GradualEnvSub x gU gu (EnvExt y gU_11 Gamma) (EnvExt y gU_22 Gamma_^))]

;; #source file ./ott/lang_simple.ott  lines 1506 - 1509 
 [
  
  (GradualEnvSub x gU gu Gamma Gamma_^)
  ------------------------------------------------------- "GradualEnvSubVarSame"
  (GradualEnvSub x gU gu (EnvExt x gU_^ Gamma) Gamma_^)]
)
;; #source file ./ott/lang_simple.ott  lines 1511 - 1511 


;;;;;;;;;;;;;;;;;
;; Judgment form versions of hereditary substitution and other related functions
;;;;;;;;;;;;;;;;

(define-judgment-form L 
 
  #:mode (GHsub I I I I O)
  #:contract (GHsub x gU gu_11 gu_22 gu_33)

  [ (where gu_33 ,(hsub (term x) (term gu_11) (term gU) (term gu_22)))
  --------------------------------------
  (GHsub x gU gu_11 gu_22 gu_33)
  ]

)

(define-judgment-form L 
 
  #:mode (Domain I O)
  #:contract (Domain gU gU_2)

  [ (where gU_2 ,(dom (term gU)))
  --------------------------------------
  (Domain gU gU_2)
  ]

)

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; Functions to substitute into the codomain of a function type
;; or the body of a function
;; Used to compute the return type and normal form (respectively) of function application.
;; Produces ? if the input is ?
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

;;; definitions 

(define-judgment-form
  L
  #:mode (CodSub I I O)
  #:contract (CodSub gu gU gU_^)

;; #source file ./ott/lang_simple.ott  lines 1689 - 1692 
 [(GHsub x gU_11 gu gU_22 gU_22^)
  ------------------------------------------------ "CodSubPi"
  (CodSub gu (CanonicalPi x gU_11 gU_22) gU_22^)]

;; #source file ./ott/lang_simple.ott  lines 1693 - 1695 
 [--------------------------------------- "CodSubDyn"
  (CodSub gu CanonicalDyn CanonicalDyn)]

)
(define-judgment-form L 
 
  #:mode (BodySub I I I O)
  #:contract (BodySub gU gu gu_22 gu_33)

;; #source file ./ott/lang_simple.ott  lines 1721 - 1724 
 [(GHsub x gU gu gu_22 gu_22^)
  ------------------------------------------------- "BodySubPi"
  (BodySub gU gu  (CanonicalLam x gu_22)  gu_22^)]

;; #source file ./ott/lang_simple.ott  lines 1725 - 1727 
 [------------------------------------------- "BodySubDyn"
  (BodySub gU gu CanonicalDyn CanonicalDyn)]
)
;; #source file ./ott/lang_simple.ott  lines 1729 - 1740 

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; Well-formedness checks for gradual canonical forms
;; GradualSet checks if there's some (Set i) that a given type checks against
;; WF checks if an environment is well formed (i.e. if each type in it checks against some Set i)
;; GCSynth synthesizes types for atomic (neutral) forms
;; And GCCheck checks a canonical form against a given type
;;
;; Consistent checks if two types are consistent i.e. equal, except for possible occurrences of ?
;; ConsistentSet checks if a type is (Set i) or ?. Used in type-checking Pi-types.
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

;;; definitions 

(define-judgment-form
  L
  #:mode (GradualSet I I)
  #:contract (GradualSet Gamma gU)

;; #source file ./ott/lang_simple.ott  lines 1753 - 1756 
 [
  (GCSynth Gamma grr CanonicalDyn)
  ------------------------------------------ "GradualSetDynTy"
  (GradualSet Gamma (CanonicalAtomic grr))]

;; #source file ./ott/lang_simple.ott  lines 1757 - 1760 
 [
  (GCSynth Gamma grr (CanonicalAtomic (AtomicSet i)))
  ------------------------------------------ "GradualSetSet"
  (GradualSet Gamma (CanonicalAtomic grr))]

;; #source file ./ott/lang_simple.ott  lines 1763 - 1768 
 [
  (GradualSet Gamma gU_11)
    
  (GradualSet (EnvExt x gU_11 Gamma) gU_22)
  ------------------------------------------------ "GradualSetPi"
  (GradualSet Gamma (CanonicalPi x gU_11 gU_22))]

;; #source file ./ott/lang_simple.ott  lines 1770 - 1772 
 [
  --------------------------------- "GradualSetDynVal"
  (GradualSet Gamma CanonicalDyn)]

)
(define-judgment-form L 
 
  #:mode (WF I)
  #:contract (WF Gamma)

;; #source file ./ott/lang_simple.ott  lines 1778 - 1780 
 [--------------- "WFEmpty"
  (WF EnvEmpty)]

;; #source file ./ott/lang_simple.ott  lines 1781 - 1785 
 [
   (WF Gamma)   (GradualSet Gamma gU) 
  (GVarFree x Gamma)
  -------------------------- "WFExt"
  (WF (EnvExt x gU Gamma))]

)
(define-judgment-form L 
 
  #:mode (GCSynth I I O)
  #:contract (GCSynth Gamma grr gU)

;; #source file ./ott/lang_simple.ott  lines 1791 - 1794 
 [
   (side-condition ,(> (term  i ) 0)) 
  --------------------------------------------------------------------------- "GCSynthSet"
  (GCSynth Gamma (AtomicSet i) (CanonicalAtomic  (AtomicSet (succ  i ) ) ))]

;; #source file ./ott/lang_simple.ott  lines 1796 - 1800 
 [
    
  (GVarLook x gU Gamma)
  --------------------------------------------------- "GCSynthVar"
  (GCSynth Gamma  (AtomicSpine  x  SpineEmpty)  gU)]

;; #source file ./ott/lang_simple.ott  lines 1804 - 1811 
 [
  (GCSynth Gamma (AtomicSpine x ge) gU)
  (Domain gU gU_22)
  (GCCheck Gamma gu gU_22)
  (CodSub gu gU gU_33)
  --------------------------------------------------------- "GCSynthApp"
  (GCSynth Gamma (AtomicSpine x (SpineCons ge gu)) gU_33)]

;; #source file ./ott/lang_simple.ott  lines 1812 - 1814 
 [
  ------------------------------------------------------------- "GCSynthNat"
  (GCSynth Gamma AtomicNat (CanonicalAtomic (AtomicSet  1 )))]

;; #source file ./ott/lang_simple.ott  lines 1815 - 1817 
 [
  -------------------------------------------------------- "GCSynthZero"
  (GCSynth Gamma AtomicZero (CanonicalAtomic AtomicNat))]

;; #source file ./ott/lang_simple.ott  lines 1818 - 1821 
 [
  (GCCheck Gamma gu (CanonicalAtomic AtomicNat))
  ------------------------------------------------------------- "GCSynthSucc"
  (GCSynth Gamma (AtomicSucc gu) (CanonicalAtomic AtomicNat))]

;; #source file ./ott/lang_simple.ott  lines 1822 - 1833 
 [
   (where   y  ,(gensym)) 
  (GCCheck Gamma (CanonicalAtomic (AtomicSpine x ge)) (CanonicalAtomic AtomicNat))
  (GCCheck Gamma gU (CanonicalPi y (CanonicalAtomic AtomicNat) (CanonicalAtomic (AtomicSet  1 ))))
  (BodySub (CanonicalAtomic AtomicNat) (CanonicalAtomic AtomicZero) gU gU_22)
  (GCCheck Gamma gu_22 gU_22)
  (BodySub (CanonicalAtomic AtomicNat) (CanonicalAtomic  (AtomicSpine  x_11  SpineEmpty) ) gU gU_33^)
  (BodySub (CanonicalAtomic AtomicNat) (CanonicalAtomic (AtomicSucc (CanonicalAtomic  (AtomicSpine  x_11  SpineEmpty) ))) gU gU_33)
  (GCCheck (EnvExt x_22 gU_33^ (EnvExt x_11 (CanonicalAtomic AtomicNat) Gamma)) gu_33 gU_33)
  (BodySub (CanonicalAtomic AtomicNat) (CanonicalAtomic (AtomicSpine x ge)) gU gU_44)
  ---------------------------------------------------------------------------------- "GCSynthNatElim"
  (GCSynth Gamma (AtomicSpine x (SpineNatElim ge gU gu_22 x_11 x_22 gu_33)) gU_44)]

)
(define-judgment-form L 
 
  #:mode (GCCheck I I I)
  #:contract (GCCheck Gamma gu gU)

;; #source file ./ott/lang_simple.ott  lines 1840 - 1844 
 [
  (GCSynth Gamma grr gU)
  (Consistent gU gU_^)
  -------------------------------------------- "GCCheckSynth"
  (GCCheck Gamma (CanonicalAtomic grr) gU_^)]

;; #source file ./ott/lang_simple.ott  lines 1845 - 1849 
 [
  (GCSynth Gamma gRR (CanonicalAtomic (AtomicSet i)))
   (side-condition ,(and (< 0 (term  i )) (<= (term  i ) (term  j )))) 
  ----------------------------------------------------------------------- "GCCheckLevel"
  (GCCheck Gamma (CanonicalAtomic gRR) (CanonicalAtomic (AtomicSet j)))]

;; #source file ./ott/lang_simple.ott  lines 1851 - 1855 

;; #source file ./ott/lang_simple.ott  lines 1857 - 1862 
 [
   (where   z  ,(gensym)) 
    
  (GCCheck (EnvExt z gU_11 Gamma)  (substitute  gu   x   z )   (substitute  gU_22   y   z ) )
  ------------------------------------------------------------------- "GCCheckLamPiRdxAlpha"
  (GCCheck Gamma  (CanonicalLam x gu)  (CanonicalPi y gU_11 gU_22))]

;; #source file ./ott/lang_simple.ott  lines 1863 - 1867 
 [
    
  (GCCheck (EnvExt x CanonicalDyn Gamma) gu CanonicalDyn)
  ---------------------------------------------------- "GCCheckLamDyn"
  (GCCheck Gamma  (CanonicalLam x gu)  CanonicalDyn)]

;; #source file ./ott/lang_simple.ott  lines 1868 - 1874 
 [
  (ConsistentSet gU_33)
  (GCCheck Gamma gU_11 gU_33)
    
  (GCCheck (EnvExt x gU_11 Gamma) gU_22 gU_33)
  --------------------------------------------------- "GCCheckPi"
  (GCCheck Gamma (CanonicalPi x gU_11 gU_22) gU_33)]

;; #source file ./ott/lang_simple.ott  lines 1876 - 1879 
 [
  (GradualSet Gamma gU)
  --------------------------------- "GCCheckDyn"
  (GCCheck Gamma CanonicalDyn gU)]

)
(define-judgment-form L 
 
  #:mode (ConsistentSet I)
  #:contract (ConsistentSet gU)

;; #source file ./ott/lang_simple.ott  lines 1887 - 1889 
 [------------------------------------------------- "ConsistentSetSet"
  (ConsistentSet (CanonicalAtomic (AtomicSet i)))]

;; #source file ./ott/lang_simple.ott  lines 1890 - 1892 
 [------------------------------ "ConsistentSetDyn"
  (ConsistentSet CanonicalDyn)]

)
(define-judgment-form L 
 
  #:mode (Consistent I I)
  #:contract (Consistent gU gU_^)

;; #source file ./ott/lang_simple.ott  lines 1902 - 1904 
 [-------------------- "ConsistentEq"
  (Consistent gu gu)]

;; #source file ./ott/lang_simple.ott  lines 1905 - 1909 

;; #source file ./ott/lang_simple.ott  lines 1911 - 1916 
 [ (where   z  ,(gensym)) 
  (Consistent gU_11 gU_11^)
  (Consistent  (substitute  gU_22   x   z )   (substitute  gU_22^   y   z ) )
  ------------------------------------------------------------------------ "ConsistentPiRdxAlpha"
  (Consistent (CanonicalPi x gU_11 gU_22) (CanonicalPi y gU_11^ gU_22^))]

;; #source file ./ott/lang_simple.ott  lines 1917 - 1920 

;; #source file ./ott/lang_simple.ott  lines 1922 - 1926 
 [ (where   z  ,(gensym)) 
  (Consistent  (substitute  gu   x   z )   (substitute  gu_^   y   z ) )
  ------------------------------------------------------------ "ConsistentLamRdxAlpha"
  (Consistent  (CanonicalLam x gu)   (CanonicalLam y gu_^) )]

;; #source file ./ott/lang_simple.ott  lines 1927 - 1931 
 [(Consistent (CanonicalAtomic (AtomicSpine x ge)) (CanonicalAtomic (AtomicSpine x ge_^)))
  (Consistent gu gu_^)
  -------------------------------------------------------------------------------------------------------------------------- "ConsistentApp"
  (Consistent (CanonicalAtomic (AtomicSpine x (SpineCons ge gu))) (CanonicalAtomic (AtomicSpine x (SpineCons ge_^ gu_^))))]

;; #source file ./ott/lang_simple.ott  lines 1932 - 1934 
 [------------------------------ "ConsistentDynL"
  (Consistent CanonicalDyn gu)]

;; #source file ./ott/lang_simple.ott  lines 1935 - 1937 
 [------------------------------ "ConsistentDynR"
  (Consistent gu CanonicalDyn)]
)
;; #source file ./ott/lang_simple.ott  lines 1938 - 1943 

;;;;;;;;;;
;; The meet of two pieces of evidence is just the meet of the wrapped types
;;;;;;;;;;;

;;; definitions 

(define-judgment-form
  L
  #:mode (EvMeet I I O)
  #:contract (EvMeet ep_11 ep_22 ep_33)

;; #source file ./ott/lang_simple.ott  lines 1953 - 1956 
 [(Meet gU_11 gU_22 gU_33)
  ------------------------------------------------------------------- "EvMeetUnwrap"
  (EvMeet (EvidenceEv gU_11) (EvidenceEv gU_22) (EvidenceEv gU_33))]
)
;; #source file ./ott/lang_simple.ott  lines 1957 - 1957 


;;;;;;;;;;;;;;;;;;
;; Judgment-form version of Meet and our precision operation
;;;;;;;;;;;;;;;;;;

(define-judgment-form L 
 
  #:mode (Meet I I O)
  #:contract (Meet gU_11 gU_22 gU_33)

  [
  (where gU_3 ,(meet (term gU_1) (term gU_2)))
  ---------------------------------
  (Meet gU_1 gU_2 gU_3)
  ]

)

(define-judgment-form L 
 
  #:mode (MorePrecise I I)
  #:contract (MorePrecise gU gU_^)

  [
  (Meet gU_1 gU_2 gU_1)
  ---------------------------------
  (MorePrecise gU_1 gU_2)
  ]

)

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; Definitions for whether a term (not canonical form) is more precise than another
;; Used to express our version of the gradual guarantee.
;;
;; Additionally, we define EvConsistent tests whether ep is evidence that gU1 ~=~ gU2
;; It does so by seeing if ep is a wrapper around a type more precise than another
;; This is used when checking our evidence terms
;; TODO: get evidence-term typing working in Redex
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

 

;;; definitions 

(define-judgment-form
  L
  #:mode (TermPrecise I I)
  #:contract (TermPrecise gt gt_^)

;; #source file ./ott/lang_simple.ott  lines 2104 - 2108 

;; #source file ./ott/lang_simple.ott  lines 2112 - 2115 

;; #source file ./ott/lang_simple.ott  lines 2118 - 2122 
 [
  
  (TermPrecise gt_11 gt_11^)
  (TermPrecise gt_22 gt_22^)
  ------------------------------------------------------------- "TermPreciseApp"
  (TermPrecise (TermApp gt_11 gt_22) (TermApp gt_11^ gt_22^))]

;; #source file ./ott/lang_simple.ott  lines 2123 - 2127 
 [
  
  (TermPrecise gt_11 gt_22)
  (TermPrecise gT_11 gT_22)
  ----------------------------------------------------------- "TermPreciseAscr"
  (TermPrecise (TermAnn gt_11 gT_11) (TermAnn gt_22 gT_22))]

;; #source file ./ott/lang_simple.ott  lines 2128 - 2131 
 [
  -------------------------- "TermPreciseDyn"
  (TermPrecise gt TermDyn)]

;; #source file ./ott/lang_simple.ott  lines 2132 - 2134 
 [--------------------- "TermPreciseRefl"
  (TermPrecise gT gT)]

)
(define-judgment-form L 
 
  #:mode (EvPrecise I I)
  #:contract (EvPrecise ep ep_^)

;; #source file ./ott/lang_simple.ott  lines 2141 - 2144 
 [(MorePrecise gU gU_^)
  ----------------------------------------------- "EvPreciseUnwrap"
  (EvPrecise (EvidenceEv gU) (EvidenceEv gU_^))]

)
(define-judgment-form L 
 
  #:mode (EvTermPrecise I I)
  #:contract (EvTermPrecise et et_^)

;; #source file ./ott/lang_simple.ott  lines 2151 - 2155 

;; #source file ./ott/lang_simple.ott  lines 2158 - 2161 

;; #source file ./ott/lang_simple.ott  lines 2163 - 2167 
 [
  
  (EvTermPrecise et_11 et_11^)
  (EvTermPrecise et_22 et_22^)
  --------------------------------------------------------------- "EvTermPreciseApp"
  (EvTermPrecise (TermApp et_11 et_22) (TermApp et_11^ et_22^))]

;; #source file ./ott/lang_simple.ott  lines 2168 - 2172 
 [
  
  (EvTermPrecise et_11 et_22)
  (EvPrecise ep_11 ep_22)
  ----------------------------------------------------------- "EvTermPreciseAscr"
  (EvTermPrecise (TermEp ep_11 et_11) (TermEp ep_22 et_22))]

;; #source file ./ott/lang_simple.ott  lines 2173 - 2175 
 [---------------------------- "EvTermPreciseDyn"
  (EvTermPrecise eT TermDyn)]

;; #source file ./ott/lang_simple.ott  lines 2176 - 2178 
 [------------------------------ "EvTermPreciseErr"
  (EvTermPrecise TermError eT)]

;; #source file ./ott/lang_simple.ott  lines 2179 - 2181 
 [----------------------- "EvTermPreciseRefl"
  (EvTermPrecise eT eT)]

)
(define-judgment-form L 
 
  #:mode (EvConsistent I I I)
  #:contract (EvConsistent ep gU gU_^)

;; #source file ./ott/lang_simple.ott  lines 2188 - 2192 
 [(Meet gU_11 gU_22 gU_33)
  (MorePrecise gU gU_33)
  -------------------------------------------- "EvConsistentDef"
  (EvConsistent (EvidenceEv gU) gU_11 gU_22)]
)
;; #source file ./ott/lang_simple.ott  lines 2193 - 2193 
 

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; Type-checking judgments for gradual terms
;; GSynth computes the type for the given term
;; GSynth checks a term against the given type
;; The gtSynth syntactic class speeds up pattern matching by restricting us to terms that can synthesize

;;GradualSetNorm computes the normal form for a term while checking that it types against some (Set i)
;;GNSynth and GNCheck are like GSynth and GCheck, but produce an (approximate) normal form for the given term.

;; The GEta judgments to help with eta-expanding terms and neutrals
;; so that we always produce eta-long normal forms

;; GElabSynth and GElabCheck are like GSynth and GCheck, but elaborate the given term
;; into an evidence term that we can run.
;; The main change is that we drop annotations, and ascribe initial evidence wherever
;; we apply the consistency relation during typechecking, so that its applications are explicit
;; in the terms. 
;; All functons and ? occurrences are also ascribed with evidence.

;; GradualNESynth and GradualNECheck perform normalization and elaboration simultaneously,
;; which sometimes speeds us up to avoid duplicate traversals

;; The GradualSynthCheck judgments (for normalization, elaboration, and combined)
;; are optimizations to avoid computing the synthesized type of a term twice
;; when checking if we should apply universe cumulativity or consistency
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

;;; definitions 

(define-judgment-form
  L
  #:mode (GSynth I I O)
  #:contract (GSynth Gamma gtSynth gU)

;; #source file ./ott/lang_simple.ott  lines 2261 - 2265 
 [
  
  (GradualSetNorm Gamma gU gT)
  (GCheck Gamma gt gU)
  ------------------------------------- "GSynthAnn"
  (GSynth Gamma  (TermAnn gt gT)  gU)]

;; #source file ./ott/lang_simple.ott  lines 2266 - 2269 
 [
   (side-condition ,(> (term  i ) 0)) 
  ------------------------------------------------------------------------ "GSynthSet"
  (GSynth Gamma (TermSet i) (CanonicalAtomic  (AtomicSet (succ  i ) ) ))]

;; #source file ./ott/lang_simple.ott  lines 2271 - 2275 
 [
  (GVarLook x gU Gamma)
    
  ------------------------------- "GSynthVar"
  (GSynth Gamma x gU)]

;; #source file ./ott/lang_simple.ott  lines 2280 - 2285 
 [
  
   (GSynth Gamma gtSynth_11 gU)      
    (Domain gU gU_^)   (GNCheck Gamma gu gt_22 gU_^)  
  (CodSub gu gU gU_22)
  ------------------------------------------------- "GSynthApp"
  (GSynth Gamma (TermApp gtSynth_11 gt_22) gU_22)]

;; #source file ./ott/lang_simple.ott  lines 2286 - 2289 
 [
  ------------------------------------- "GSynthDyn"
  (GSynth Gamma TermDyn CanonicalDyn)]

;; #source file ./ott/lang_simple.ott  lines 2290 - 2292 
 [
  ---------------------------------------------------------- "GSynthNat"
  (GSynth Gamma TermNat (CanonicalAtomic (AtomicSet  1 )))]

;; #source file ./ott/lang_simple.ott  lines 2293 - 2295 
 [
  ----------------------------------------------------- "GSynthZero"
  (GSynth Gamma TermZero (CanonicalAtomic AtomicNat))]

;; #source file ./ott/lang_simple.ott  lines 2296 - 2299 
 [
  
  (GCheck Gamma gt (CanonicalAtomic AtomicNat))
  ---------------------------------------------------------- "GSynthSucc"
  (GSynth Gamma (TermSucc gt) (CanonicalAtomic AtomicNat))]

;; #source file ./ott/lang_simple.ott  lines 2300 - 2311 
 [
  
   (where   y  ,(gensym)) 
  (GNCheck Gamma gu_11 gt_11 (CanonicalAtomic AtomicNat))
  (GNCheck Gamma gU gT (CanonicalPi y (CanonicalAtomic AtomicNat) (CanonicalAtomic (AtomicSet  1 ))))
  (BodySub (CanonicalAtomic AtomicNat) (CanonicalAtomic AtomicZero) gU gU_22)
  (GCheck Gamma gt_22 gU_22)
  (BodySub (CanonicalAtomic AtomicNat) (CanonicalAtomic  (AtomicSpine  x_11  SpineEmpty) ) gU gU_33^)
  (BodySub (CanonicalAtomic AtomicNat) (CanonicalAtomic (AtomicSucc (CanonicalAtomic  (AtomicSpine  x_11  SpineEmpty) ))) gU gU_33)
  (GCheck (EnvExt x_22 gU_33^ (EnvExt x_11 (CanonicalAtomic AtomicNat) Gamma)) gt_33 gU_33)
  (BodySub (CanonicalAtomic AtomicNat) gu_11 gU gU_44)
  ------------------------------------------------------------------- "GSynthNatElim"
  (GSynth Gamma (TermNatElim gt_11 gT gt_22 x_11 x_22 gt_33) gU_44)]

)
(define-judgment-form L 
 
  #:mode (GCheck I I I)
  #:contract (GCheck Gamma gt gU)

;; #source file ./ott/lang_simple.ott  lines 2327 - 2332 
 [
  
  (GSynth Gamma gtSynth gU_^)
  (Consistent gU_^ gU)
  --------------------------- "GCheckSynth"
  (GCheck Gamma gtSynth gU)]

;; #source file ./ott/lang_simple.ott  lines 2333 - 2338 
 [
  (GSynth Gamma gTSynth (CanonicalAtomic (AtomicSet i)))
   (side-condition ,(and (< 0 (term  i )) (<= (term  i ) (term  j )))) 
  -------------------------------------------------------- "GCheckLevel"
  (GCheck Gamma gTSynth (CanonicalAtomic (AtomicSet j)))]

;; #source file ./ott/lang_simple.ott  lines 2347 - 2351 
 [
  
   (GNCheck Gamma gU_^ gT_11 gU)   (ConsistentSet gU) 
        (GCheck (EnvExt x gU_^ Gamma) gT_22 gU) 
  ------------------------------------------ "GCheckPi"
  (GCheck Gamma (TermPi x gT_11 gT_22) gU)]

;; #source file ./ott/lang_simple.ott  lines 2353 - 2357 

;; #source file ./ott/lang_simple.ott  lines 2359 - 2364 
 [
  
   (where   z  ,(gensym)) 
    
  (GCheck (EnvExt z gU_11 Gamma)  (substitute  gt   x   z )   (substitute  gU_22   y   z ) )
  ------------------------------------------------------------- "GCheckLamPiRdxAlpha"
  (GCheck Gamma  (TermLam x gt)  (CanonicalPi y gU_11 gU_22))]

;; #source file ./ott/lang_simple.ott  lines 2366 - 2370 
 [
  
    
  (GCheck (EnvExt x CanonicalDyn Gamma) gt CanonicalDyn)
  ---------------------------------------------- "GCheckLamDyn"
  (GCheck Gamma  (TermLam x gt)  CanonicalDyn)]

)
(define-judgment-form L 
 
  #:mode (GradualSetNorm I O I)
  #:contract (GradualSetNorm Gamma gU TT)

;; #source file ./ott/lang_simple.ott  lines 2388 - 2391 
 [
  
  (GNSynth Gamma TTSynth gU (CanonicalAtomic (AtomicSet i)))
  ----------------------------------- "GradualSetNormSynth"
  (GradualSetNorm Gamma gU TTSynth)]

;; #source file ./ott/lang_simple.ott  lines 2393 - 2397 
 [
  (GradualSetNorm Gamma gU_11 TT_1_1)
  (GradualSetNorm (EnvExt x gU_11 Gamma) gU_22 TT_2_2)
  ----------------------------------------------------------------------------- "GradualSetNormPi"
  (GradualSetNorm Gamma (CanonicalPi x gU_11 gU_22) (TermPi x TT_1_1 TT_2_2))]

;; #source file ./ott/lang_simple.ott  lines 2399 - 2401 
 [
  --------------------------------------------- "GradualSetNormDyn"
  (GradualSetNorm Gamma CanonicalDyn TermDyn)]

)
(define-judgment-form L 
 
  #:mode (GEtaLong I I)
  #:contract (GEtaLong gu gU)

;; #source file ./ott/lang_simple.ott  lines 2407 - 2409 
 [-------------------------------------------------------- "GEtaLongAtomic"
  (GEtaLong (CanonicalAtomic grr) (CanonicalAtomic gRR))]

;; #source file ./ott/lang_simple.ott  lines 2410 - 2412 
 [----------------------------------------------- "GEtaLongAtomicDyn"
  (GEtaLong (CanonicalAtomic grr) CanonicalDyn)]

;; #source file ./ott/lang_simple.ott  lines 2414 - 2417 

;; #source file ./ott/lang_simple.ott  lines 2418 - 2422 
 [ (where   z  ,(gensym)) 
  (GEtaLong  (substitute  gu   x   z )   (substitute  gU   y   z ) )
  ---------------------------------------------------------- "GEtaLongLamRdxAlpha"
  (GEtaLong  (CanonicalLam x gu)  (CanonicalPi y gU_^ gU))]

;; #source file ./ott/lang_simple.ott  lines 2423 - 2425 
 [---------------------------- "GEtaLongDyn"
  (GEtaLong CanonicalDyn gU)]

;; #source file ./ott/lang_simple.ott  lines 2426 - 2428 
 [------------------------------------------ "GEtaLongPi"
  (GEtaLong (CanonicalPi x gU gU_^) gU_^^)]

)
(define-judgment-form L 
 
  #:mode (GEtaExpand I O I)
  #:contract (GEtaExpand grr gu gU)

;; #source file ./ott/lang_simple.ott  lines 2434 - 2436 
 [-------------------------------------------------------------- "GEtaExpandAtomic"
  (GEtaExpand grr (CanonicalAtomic grr) (CanonicalAtomic gRR))]

;; #source file ./ott/lang_simple.ott  lines 2437 - 2439 
 [----------------------------------------------------- "GEtaExpandDyn"
  (GEtaExpand grr (CanonicalAtomic grr) CanonicalDyn)]

;; #source file ./ott/lang_simple.ott  lines 2441 - 2445 
 [(GEtaExpand  (AtomicSpine  y  SpineEmpty)  gu gU_11)
  (GEtaExpand (AtomicSpine x (SpineCons ge gu)) gu_22 gU_22)
  -------------------------------------------------------------------------------------- "GEtaExpandPi"
  (GEtaExpand (AtomicSpine x ge)  (CanonicalLam y gu_22)  (CanonicalPi y gU_11 gU_22))]

)
(define-judgment-form L 
 
  #:mode (GEtaExpandC I O I)
  #:contract (GEtaExpandC gu gu_^ gU)

;; #source file ./ott/lang_simple.ott  lines 2452 - 2455 
 [(GEtaExpand grr gu gU)
  ------------------------------------------- "GEtaExpandCAtomic"
  (GEtaExpandC (CanonicalAtomic grr) gu gU)]

;; #source file ./ott/lang_simple.ott  lines 2456 - 2459 

;; #source file ./ott/lang_simple.ott  lines 2460 - 2464 
 [ (where   z  ,(gensym)) 
  (GEtaExpandC  (substitute  gu   x   z )  gu_^  (substitute  gU_22   x   z ) )
  ----------------------------------------------------------------------------------------- "GEtaExpandCLamRdxAlpha"
  (GEtaExpandC  (CanonicalLam x gu)   (CanonicalLam z gu_^)  (CanonicalPi y gU_11 gU_22))]

;; #source file ./ott/lang_simple.ott  lines 2465 - 2469 
 [(GEtaExpandC gU_11 gU_11^ gU_^^)
  (GEtaExpandC gU_22 gU_22^ gU_^^)
  ------------------------------------------------------------------------------- "GEtaExpandCPi"
  (GEtaExpandC (CanonicalPi x gU_11 gU_22) (CanonicalPi x gU_11^ gU_22^) gU_^^)]

;; #source file ./ott/lang_simple.ott  lines 2471 - 2473 
 [-------------------------------------------- "GEtaExpandCDyn"
  (GEtaExpandC CanonicalDyn CanonicalDyn gU)]

;; #source file ./ott/lang_simple.ott  lines 2474 - 2476 
 [---------------------------------- "GEtaExpandCDynType"
  (GEtaExpandC gu gu CanonicalDyn)]

)
(define-judgment-form L 
 
  #:mode (GNSynth I I O O)
  #:contract (GNSynth Gamma tt gu gU)

;; #source file ./ott/lang_simple.ott  lines 2497 - 2501 
 [
  
  (GradualSetNorm Gamma gU gT)
  (GNCheck Gamma gu gt gU)
  ----------------------------------------- "GNSynthAnn"
  (GNSynth Gamma  (TermAnn gt gT)  gu gU)]

;; #source file ./ott/lang_simple.ott  lines 2502 - 2505 
 [
   (side-condition ,(> (term  i ) 0)) 
  --------------------------------------------------------------------------------------------------------- "GNSynthSet"
  (GNSynth Gamma (TermSet i) (CanonicalAtomic (AtomicSet i)) (CanonicalAtomic  (AtomicSet (succ  i ) ) ))]

;; #source file ./ott/lang_simple.ott  lines 2507 - 2513 
 [
   (side-condition ,(not (hash-has-key? currently-defined-vars (term  x )) )) 
    
  (GVarLook x gU Gamma)
  (GEtaExpand  (AtomicSpine  x  SpineEmpty)  gu gU)
  ----------------------------------- "GNSynthVar"
  (GNSynth Gamma x gu gU)]

;; #source file ./ott/lang_simple.ott  lines 2514 - 2517 
 [
  
   (where (ENTTriple  et   gu   gU ) ,(and (hash-has-key? currently-defined-vars (term  x ) ) (hash-ref currently-defined-vars (term  x )) )) 
  ----------------------------------- "GNSynthVarLook"
  (GNSynth Gamma x gu gU)]

;; #source file ./ott/lang_simple.ott  lines 2522 - 2529 
 [
      (where   x  ,(gensym))    (GNSynth Gamma tt_11 gu_11 gU)    (GEtaExpandC gu_11 gu_11^ (CanonicalPi x CanonicalDyn CanonicalDyn))  
    
   (Domain gU gU_11)   (GNCheck Gamma gu_22 tt_22 gU_11) 
  (BodySub gU_11 gu_22 gu_11^ gu_33)
   (CodSub gu_22 gU gU_22)   (GEtaExpandC gu_33 gu_33^ gU_22) 
  ---------------------------------------------------- "GNSynthApp"
  (GNSynth Gamma (TermApp tt_11 tt_22) gu_33^ gU_22)]

;; #source file ./ott/lang_simple.ott  lines 2531 - 2534 
 [
  --------------------------------------------------- "GNSynthDyn"
  (GNSynth Gamma TermDyn CanonicalDyn CanonicalDyn)]

;; #source file ./ott/lang_simple.ott  lines 2535 - 2538 
 [
  
  (GNCheck Gamma gu et gU)
  --------------------------------------------------- "GNSynthEv"
  (GNSynth Gamma (TermEp (EvidenceEv gU) et) gu gU)]

;; #source file ./ott/lang_simple.ott  lines 2539 - 2541 
 [
  --------------------------------------------------------------------------------------- "GNSynthNat"
  (GNSynth Gamma TermNat (CanonicalAtomic AtomicNat) (CanonicalAtomic (AtomicSet  1 )))]

;; #source file ./ott/lang_simple.ott  lines 2542 - 2544 
 [
  ----------------------------------------------------------------------------------- "GNSynthZero"
  (GNSynth Gamma TermZero (CanonicalAtomic AtomicZero) (CanonicalAtomic AtomicNat))]

;; #source file ./ott/lang_simple.ott  lines 2545 - 2548 
 [
  
  (GNCheck Gamma gu gt (CanonicalAtomic AtomicNat))
  --------------------------------------------------------------------------------------------- "GNSynthSucc"
  (GNSynth Gamma (TermSucc gt) (CanonicalAtomic (AtomicSucc gu)) (CanonicalAtomic AtomicNat))]

;; #source file ./ott/lang_simple.ott  lines 2549 - 2562 
 [
  
   (where   y  ,(gensym)) 
  (GNCheck Gamma gu_11 gt_11 (CanonicalAtomic AtomicNat))
  (GNCheck Gamma gU gT (CanonicalPi y (CanonicalAtomic AtomicNat) (CanonicalAtomic (AtomicSet  1 ))))
  (BodySub (CanonicalAtomic AtomicNat) (CanonicalAtomic AtomicZero) gU gU_22)
  (GNCheck Gamma gu_22 gt_22 gU_22)
  (BodySub (CanonicalAtomic AtomicNat) (CanonicalAtomic  (AtomicSpine  x_11  SpineEmpty) ) gU gU_33^)
  (BodySub (CanonicalAtomic AtomicNat) (CanonicalAtomic (AtomicSucc (CanonicalAtomic  (AtomicSpine  x_11  SpineEmpty) ))) gU gU_33)
  (GNCheck (EnvExt x_22 gU_33^ (EnvExt x_11 (CanonicalAtomic AtomicNat) Gamma)) gu_33 gt_33 gU_33)
  (BodySub (CanonicalAtomic AtomicNat) gu_11 gU gU_44)
   (where   z  ,(gensym)) 
  (GHsub z (CanonicalAtomic AtomicNat) gu_11 (CanonicalAtomic (AtomicSpine z (SpineNatElim SpineEmpty gU gu_22 x_11 x_22 gu_33))) gu_44)
  -------------------------------------------------------------------------- "GNSynthNatElim"
  (GNSynth Gamma (TermNatElim gt_11 gT gt_22 x_11 x_22 gt_33) gu_44 gU_44)]

)
(define-judgment-form L 
 
  #:mode (GNSynthCheck I O I I I I)
  #:contract (GNSynthCheck Gamma gu ttSynth gu_^ gU_^ gU)

;; #source file ./ott/lang_simple.ott  lines 2569 - 2572 
 [
   (side-condition ,(and (< 0 (term  i )) (<= (term  i ) (term  j )))) 
  ---------------------------------------------------------------------------------------------------- "GNSynthCheckLevel"
  (GNSynthCheck Gamma gU TTSynth gU (CanonicalAtomic (AtomicSet i)) (CanonicalAtomic (AtomicSet j)))]

;; #source file ./ott/lang_simple.ott  lines 2573 - 2578 
 [
  
   (side-condition ,(not (judgment-holds (BothSets  gU   gU_^ )) )) 
  (Meet gU gU_^ gU_^^)
   (where  gu  ,(if (alpha-equivalent? (term  gU_^ ) (term  gU_^^ )) (term  gu ) (term  CanonicalDyn ))) 
  -------------------------------------------- "GNSynthCheckConsistent"
  (GNSynthCheck Gamma gu ttSynth gu gU_^ gU)]

)
(define-judgment-form L 
 
  #:mode (GNCheck I O I I)
  #:contract (GNCheck Gamma gu tt gU)

;; #source file ./ott/lang_simple.ott  lines 2586 - 2590 
 [
  
  (GNSynth Gamma ttSynth gu_^ gU_^)
  (GNSynthCheck Gamma gu ttSynth gu_^ gU_^ gU)
  ------------------------------- "GNCheckSynthRdx"
  (GNCheck Gamma gu ttSynth gU)]

;; #source file ./ott/lang_simple.ott  lines 2591 - 2597 

;; #source file ./ott/lang_simple.ott  lines 2599 - 2605 

;; #source file ./ott/lang_simple.ott  lines 2606 - 2611 

;; #source file ./ott/lang_simple.ott  lines 2613 - 2621 
 [
  (ConsistentSet gU_33)
  (GNCheck Gamma gU_11 TT_11 gU_33)
    
  (GNCheck (EnvExt x gU_11 Gamma) gU_22 TT_22 gU_33)
  -------------------------------------------------------------------------- "GNCheckPi"
  (GNCheck Gamma (CanonicalPi x gU_11 gU_22) (TermPi x TT_11 TT_22) gU_33)]

;; #source file ./ott/lang_simple.ott  lines 2622 - 2626 

;; #source file ./ott/lang_simple.ott  lines 2627 - 2632 
 [
   (where   z  ,(gensym)) 
    
  (GNCheck (EnvExt z gU_11 Gamma) gu  (substitute  tt   x   z )   (substitute  gU_22   y   z ) )
  ------------------------------------------------------------------------------------ "GNCheckLamPiRdxAlpha"
  (GNCheck Gamma  (CanonicalLam z gu)   (TermLam x tt)  (CanonicalPi y gU_11 gU_22))]

;; #source file ./ott/lang_simple.ott  lines 2633 - 2637 
 [
    
  (GNCheck (EnvExt x CanonicalDyn Gamma) gu tt CanonicalDyn)
  --------------------------------------------------------------------- "GNCheckLamDyn"
  (GNCheck Gamma  (CanonicalLam x gu)   (TermLam x tt)  CanonicalDyn)]

)
(define-judgment-form L 
 
  #:mode (GElabSynth I I O O)
  #:contract (GElabSynth Gamma gtSynth et gU)

;; #source file ./ott/lang_simple.ott  lines 2660 - 2664 
 [
  
  (GradualSetNorm Gamma gU gT)
  (GElabCheck Gamma et gt gU)
  -------------------------------------------- "GElabSynthAnn"
  (GElabSynth Gamma  (TermAnn gt gT)  et gU)]

;; #source file ./ott/lang_simple.ott  lines 2665 - 2668 
 [
   (side-condition ,(> (term  i ) 0)) 
  ---------------------------------------------------------------------------------------- "GElabSynthSet"
  (GElabSynth Gamma (TermSet i) (TermSet i) (CanonicalAtomic  (AtomicSet (succ  i ) ) ))]

;; #source file ./ott/lang_simple.ott  lines 2670 - 2675 
 [
   (side-condition ,(not (hash-has-key? currently-defined-vars (term  x )) )) 
    
  (GVarLook x gU Gamma)
  ----------------------------------------------- "GElabSynthVar"
  (GElabSynth Gamma x x gU)]

;; #source file ./ott/lang_simple.ott  lines 2676 - 2679 
 [
  
   (where (ENTTriple  et   gu   gU ) ,(and (hash-has-key? currently-defined-vars (term  x ) ) (hash-ref currently-defined-vars (term  x )) )) 
  ----------------------------------------------- "GElabSynthVarLook"
  (GElabSynth Gamma x x gU)]

;; #source file ./ott/lang_simple.ott  lines 2683 - 2689 
 [
  
  (GElabSynth Gamma gtSynth_11 et_11 gU)
  (Domain gU gU_11)
  (GradualNECheck Gamma gu et_22 gt_22 gU_11)
  (CodSub gu gU gU_22)
  ----------------------------------------------------------------------------------------------------------------------------------------------------------- "GElabSynthApp"
  (GElabSynth Gamma (TermApp gtSynth_11 gt_22) (TermApp  (TermEp (EvidenceEv  (CanonicalPi ,(gensym)  CanonicalDyn   CanonicalDyn ) ) et_11)  et_22) gU_22)]

;; #source file ./ott/lang_simple.ott  lines 2690 - 2693 
 [
  ------------------------------------------------------------------------------------ "GElabSynthDyn"
  (GElabSynth Gamma TermDyn (TermEp (EvidenceEv CanonicalDyn) TermDyn) CanonicalDyn)]

;; #source file ./ott/lang_simple.ott  lines 2694 - 2696 
 [
  ---------------------------------------------------------------------- "GElabSynthNat"
  (GElabSynth Gamma TermNat TermNat (CanonicalAtomic (AtomicSet  1 )))]

;; #source file ./ott/lang_simple.ott  lines 2697 - 2699 
 [
  ------------------------------------------------------------------ "GElabSynthZero"
  (GElabSynth Gamma TermZero TermZero (CanonicalAtomic AtomicNat))]

;; #source file ./ott/lang_simple.ott  lines 2700 - 2703 
 [
  
  (GElabCheck Gamma et gt (CanonicalAtomic AtomicNat))
  ---------------------------------------------------------------------------- "GElabSynthSucc"
  (GElabSynth Gamma (TermSucc gt) (TermSucc et) (CanonicalAtomic AtomicNat))]

;; #source file ./ott/lang_simple.ott  lines 2704 - 2715 
 [
  
   (where   y  ,(gensym)) 
  (GradualNECheck Gamma gu_11 et_11 gt_11 (CanonicalAtomic AtomicNat))
  (GradualNECheck Gamma gU eT gT (CanonicalPi y (CanonicalAtomic AtomicNat) (CanonicalAtomic (AtomicSet  1 ))))
  (BodySub (CanonicalAtomic AtomicNat) (CanonicalAtomic AtomicZero) gU gU_22)
  (GElabCheck Gamma et_22 gt_22 gU_22)
  (BodySub (CanonicalAtomic AtomicNat) (CanonicalAtomic  (AtomicSpine  x_11  SpineEmpty) ) gU gU_33^)
  (BodySub (CanonicalAtomic AtomicNat) (CanonicalAtomic (AtomicSucc (CanonicalAtomic  (AtomicSpine  x_11  SpineEmpty) ))) gU gU_33)
  (GElabCheck (EnvExt x_22 gU_33^ (EnvExt x_11 (CanonicalAtomic AtomicNat) Gamma)) et_33 gt_33 gU_33)
  (BodySub (CanonicalAtomic AtomicNat) gu_11 gU gU_44)
  -------------------------------------------------------------------------------------------------------------------- "GElabSynthNatElim"
  (GElabSynth Gamma (TermNatElim gt_11 gT gt_22 x_11 x_22 gt_33) (TermNatElim et_11 eT et_22 x_11 x_22 et_33) gU_44)]

)
(define-judgment-form L 
 
  #:mode (GElabSynthCheck I O I I I I)
  #:contract (GElabSynthCheck Gamma et_^ gtSynth et gU_^ gU)

;; #source file ./ott/lang_simple.ott  lines 2722 - 2725 
 [
   (side-condition ,(and (< 0 (term  i )) (<= (term  i ) (term  j )))) 
  ------------------------------------------------------------------------------------------------------- "GElabSynthCheckLevel"
  (GElabSynthCheck Gamma eT gTSynth eT (CanonicalAtomic (AtomicSet i)) (CanonicalAtomic (AtomicSet j)))]

;; #source file ./ott/lang_simple.ott  lines 2729 - 2734 
 [
  
   (side-condition ,(not (judgment-holds (BothSets  gU_^^   gU )) )) 
  (Meet gU_^^ gU gU_^)
  --------------------------------------------------------------------------- "GElabSynthCheckConsistent"
  (GElabSynthCheck Gamma (TermEp (EvidenceEv gU_^) et) gtSynth et gU gU_^^)]

)
(define-judgment-form L 
 
  #:mode (GElabCheck I O I I)
  #:contract (GElabCheck Gamma et gt gU)

;; #source file ./ott/lang_simple.ott  lines 2748 - 2753 
 [
  
  (GElabSynth Gamma gtSynth et_^ gU_^)
  (GElabSynthCheck Gamma et gtSynth et_^ gU_^ gU)
  ---------------------------------- "GElabCheckSynthRdx"
  (GElabCheck Gamma et gtSynth gU)]

;; #source file ./ott/lang_simple.ott  lines 2754 - 2760 

;; #source file ./ott/lang_simple.ott  lines 2761 - 2766 

;; #source file ./ott/lang_simple.ott  lines 2776 - 2784 
 [
  (ConsistentSet gU)
  (GradualNECheck Gamma gU_11 eT_11 gT_11 gU)
    
  (GElabCheck (EnvExt x gU_11 Gamma) eT_22 gT_22 gU)
  --------------------------------------------------------------------- "GElabCheckPi"
  (GElabCheck Gamma (TermPi x eT_11 eT_22) (TermPi x gT_11 gT_22) gU)]

;; #source file ./ott/lang_simple.ott  lines 2785 - 2789 

;; #source file ./ott/lang_simple.ott  lines 2790 - 2796 
 [
  
   (where   z  ,(gensym)) 
    
  (GElabCheck (EnvExt z gU_11 Gamma) et  (substitute  gt   x   z )   (substitute  gU_22   y   z ) )
  ------------------------------------------------------------------------------------------------------------------------------------------------------------- "GElabCheckLamPiRdxAlpha"
  (GElabCheck Gamma (TermEp (EvidenceEv (CanonicalPi z gU_11  (substitute  gU_22   y   z ) ))  (TermLam z et) )  (TermLam x gt)  (CanonicalPi y gU_11 gU_22))]

;; #source file ./ott/lang_simple.ott  lines 2797 - 2801 
 [
  
    
  (GElabCheck (EnvExt x CanonicalDyn Gamma) et gt CanonicalDyn)
  ------------------------------------------------------------------------------------------------------ "GElabCheckLamDyn"
  (GElabCheck Gamma (TermEp (EvidenceEv CanonicalDyn)  (TermLam x et) )  (TermLam x gt)  CanonicalDyn)]

)
(define-judgment-form L 
 
  #:mode (GradualNESynth I I O O O)
  #:contract (GradualNESynth Gamma gtSynth et gu gU)

;; #source file ./ott/lang_simple.ott  lines 2817 - 2821 
 [
  
  (GradualSetNorm Gamma gU gT)
  (GradualNECheck Gamma gu et gt gU)
  --------------------------------------------------- "GradualNESynthAnn"
  (GradualNESynth Gamma  (TermAnn gt gT)  et gu gU)]

;; #source file ./ott/lang_simple.ott  lines 2822 - 2825 
 [
   (side-condition ,(> (term  i ) 0)) 
  ---------------------------------------------------------------------------------------------------------------------------- "GradualNESynthSet"
  (GradualNESynth Gamma (TermSet i) (TermSet i) (CanonicalAtomic (AtomicSet i)) (CanonicalAtomic  (AtomicSet (succ  i ) ) ))]

;; #source file ./ott/lang_simple.ott  lines 2827 - 2833 
 [
   (side-condition ,(not (hash-has-key? currently-defined-vars (term  x )) )) 
    
  (GVarLook x gU Gamma)
  (GEtaExpand  (AtomicSpine  x  SpineEmpty)  gu gU)
  ------------------------------------------------------ "GradualNESynthVar"
  (GradualNESynth Gamma x x gu gU)]

;; #source file ./ott/lang_simple.ott  lines 2834 - 2837 
 [
  
   (where (ENTTriple  et   gu   gU ) ,(and (hash-has-key? currently-defined-vars (term  x ) ) (hash-ref currently-defined-vars (term  x )) )) 
  ------------------------------------------------------ "GradualNESynthVarLook"
  (GradualNESynth Gamma x x gu gU)]

;; #source file ./ott/lang_simple.ott  lines 2841 - 2851 
 [
  
  (GradualNESynth Gamma gtSynth_11 et_11 gu gU)
     (where   x  ,(gensym))    (GEtaExpandC gu gu_^ (CanonicalPi x CanonicalDyn CanonicalDyn))  
    
  (Domain gU gU_11)
  (GradualNECheck Gamma gu_22 et_22 gt_22 gU_11)
  (BodySub gU_11 gu_22 gu_^ gu_^^)
  (CodSub gu_22 gU gU_22)
  (GEtaExpandC gu_^^ gu_^^^ gU_22)
  ---------------------------------------------------------------------------------------------------------------------------------------------------------------------- "GradualNESynthApp"
  (GradualNESynth Gamma (TermApp gtSynth_11 gt_22) (TermApp  (TermEp (EvidenceEv  (CanonicalPi ,(gensym)  CanonicalDyn   CanonicalDyn ) ) et_11)  et_22) gu_^^^ gU_22)]

;; #source file ./ott/lang_simple.ott  lines 2853 - 2855 
 [
  ------------------------------------------------------------------------------------------------------ "GradualNESynthNat"
  (GradualNESynth Gamma TermNat TermNat (CanonicalAtomic AtomicNat) (CanonicalAtomic (AtomicSet  1 )))]

;; #source file ./ott/lang_simple.ott  lines 2856 - 2858 
 [
  --------------------------------------------------------------------------------------------------- "GradualNESynthZero"
  (GradualNESynth Gamma TermZero TermZero (CanonicalAtomic AtomicZero) (CanonicalAtomic AtomicNat))]

;; #source file ./ott/lang_simple.ott  lines 2859 - 2862 
 [
  
  (GradualNECheck Gamma gu et gt (CanonicalAtomic AtomicNat))
  ------------------------------------------------------------------------------------------------------------------ "GradualNESynthSucc"
  (GradualNESynth Gamma (TermSucc gt) (TermSucc et) (CanonicalAtomic (AtomicSucc gu)) (CanonicalAtomic AtomicNat))]

;; #source file ./ott/lang_simple.ott  lines 2863 - 2876 
 [
  
   (where   y  ,(gensym)) 
  (GradualNECheck Gamma gu_11 et_11 gt_11 (CanonicalAtomic AtomicNat))
  (GradualNECheck Gamma gU eT gT (CanonicalPi y (CanonicalAtomic AtomicNat) (CanonicalAtomic (AtomicSet  1 ))))
  (BodySub (CanonicalAtomic AtomicNat) (CanonicalAtomic AtomicZero) gU gU_22)
  (GradualNECheck Gamma gu_22 et_22 gt_22 gU_22)
  (BodySub (CanonicalAtomic AtomicNat) (CanonicalAtomic  (AtomicSpine  x_11  SpineEmpty) ) gU gU_33^)
  (BodySub (CanonicalAtomic AtomicNat) (CanonicalAtomic (AtomicSucc (CanonicalAtomic  (AtomicSpine  x_11  SpineEmpty) ))) gU gU_33)
  (GradualNECheck (EnvExt x_22 gU_33^ (EnvExt x_11 (CanonicalAtomic AtomicNat) Gamma)) gu_33 et_33 gt_33 gU_33)
  (BodySub (CanonicalAtomic AtomicNat) gu_11 gU gU_44)
   (where   z  ,(gensym)) 
  (GHsub z (CanonicalAtomic AtomicNat) gu_11 (CanonicalAtomic (AtomicSpine z (SpineNatElim SpineEmpty gU gu_22 x_11 x_22 gu_33))) gu_44)
  ------------------------------------------------------------------------------------------------------------------------------ "GradualNESynthNatElim"
  (GradualNESynth Gamma (TermNatElim gt_11 gT gt_22 x_11 x_22 gt_33) (TermNatElim et_11 eT et_22 x_11 x_22 et_33) gu_44 gU_44)]

)
(define-judgment-form L 
 
  #:mode (BothSets I I)
  #:contract (BothSets gU gU_^)

;; #source file ./ott/lang_simple.ott  lines 2887 - 2889 
 [---------------------------------------------------------------------------- "BothSetsRule"
  (BothSets (CanonicalAtomic (AtomicSet i)) (CanonicalAtomic (AtomicSet j)))]

)
(define-judgment-form L 
 
  #:mode (GradualNESynthCheck I O O I I I I I)
  #:contract (GradualNESynthCheck Gamma gu et_11 gtSynth gu_^ et gU_^ gU)

;; #source file ./ott/lang_simple.ott  lines 2895 - 2898 
 [
   (side-condition ,(and (< 0 (term  i )) (<= (term  i ) (term  j )))) 
  ----------------------------------------------------------------------------------------------------------------- "GradualNESynthCheckLevel"
  (GradualNESynthCheck Gamma gU eT gTSynth gU eT (CanonicalAtomic (AtomicSet i)) (CanonicalAtomic (AtomicSet j)))]

;; #source file ./ott/lang_simple.ott  lines 2903 - 2908 
 [
  
   (side-condition ,(not (judgment-holds (BothSets  gU   gU_^ )) )) 
  (Meet gU gU_^ gU_^^)
   (where  gu_^^  ,(if (alpha-equivalent? (term  gU_^ ) (term  gU_^^ )) (term  gu_^ ) (term  CanonicalDyn ))) 
  ---------------------------------------------------------------------------------------------- "GradualNESynthCheckConsistent"
  (GradualNESynthCheck Gamma gu_^^ (TermEp (EvidenceEv gU_^^) et_^) gtSynth gu_^ et_^ gU_^ gU)]

)
(define-judgment-form L 
 
  #:mode (GradualNECheck I O O I I)
  #:contract (GradualNECheck Gamma gu et gt gU)

;; #source file ./ott/lang_simple.ott  lines 2925 - 2929 
 [
  
  (GradualNESynth Gamma gtSynth et_^ gu_^ gU_^)
  (GradualNESynthCheck Gamma gu_^^ et_^^ gtSynth gu_^ et_^ gU_^ gU)
  ----------------------------------------------- "GradualNECheckSynthRdx"
  (GradualNECheck Gamma gu_^^ et_^^ gtSynth gU)]

;; #source file ./ott/lang_simple.ott  lines 2931 - 2938 

;; #source file ./ott/lang_simple.ott  lines 2939 - 2944 

;; #source file ./ott/lang_simple.ott  lines 2954 - 2962 
 [
  (ConsistentSet gU_^^)
  (GradualNECheck Gamma gU_11 eT_11 gT_11 gU_^^)
    
  (GradualNECheck (EnvExt x gU_11 Gamma) gU_22 eT_22 gT_22 gU_^^)
  -------------------------------------------------------------------------------------------------------- "GradualNECheckPi"
  (GradualNECheck Gamma (CanonicalPi x gU_11 gU_22) (TermPi x eT_11 eT_22) (TermPi x gT_11 gT_22) gU_^^)]

;; #source file ./ott/lang_simple.ott  lines 2963 - 2967 

;; #source file ./ott/lang_simple.ott  lines 2968 - 2973 
 [
  
   (where   z  ,(gensym)) 
    
  (GradualNECheck (EnvExt z gU_11 Gamma) gu et  (substitute  gt   x   z )   (substitute  gU_22   y   z ) )
  ------------------------------------------------------------------------------------------------------------ "GradualNECheckLamPiRdxAlpha"
  (GradualNECheck Gamma  (CanonicalLam z gu)   (TermLam z et)   (TermLam x gt)  (CanonicalPi y gU_11 gU_22))]

;; #source file ./ott/lang_simple.ott  lines 2974 - 2978 
 [
  
    
  (GradualNECheck (EnvExt x CanonicalDyn Gamma) gu et gt CanonicalDyn)
  --------------------------------------------------------------------------------------------- "GradualNECheckLamDyn"
  (GradualNECheck Gamma  (CanonicalLam x gu)   (TermLam x et)   (TermLam x gt)  CanonicalDyn)]

;; #source file ./ott/lang_simple.ott  lines 2979 - 2982 
 [
  (GradualSet Gamma gU)
  --------------------------------------------------------------------------------- "GradualNECheckDyn"
  (GradualNECheck Gamma CanonicalDyn (TermEp (EvidenceEv gU) TermDyn) TermDyn gU)]
)
;; #source file ./ott/lang_simple.ott  lines 2990 - 2990 
 

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; The dynamic semantics for programs
;; We merge layered evidence, and compose evidence when applying functions
;; The meet and dom functiosn throw exceptions (i.e. runtime type errors)
;; any time the meet or domains do not exist
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

;;; definitions 

(define-judgment-form
  L
  #:mode (Step I O)
  #:contract (Step et_11 et_22)

;; #source file ./ott/lang_simple.ott  lines 3110 - 3113 
 [
  (EvMeet ep_11 ep_22 ep_33)
  ------------------------------------------------------------- "StepAscr"
  (Step (TermEp ep_11  (TermEp ep_22 rv) ) (TermEp ep_33 rv))]

;; #source file ./ott/lang_simple.ott  lines 3116 - 3120 

;; #source file ./ott/lang_simple.ott  lines 3132 - 3137 
 [
  
  (Meet gU_33 gU_11 gU_11^)
  (GNCheck EnvEmpty gu rv gU_11^)
  (GHsub y gU_11^ gu gU_22 gU_22^)
  --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- "StepAppEv"
  (Step (TermApp  (TermEp (EvidenceEv (CanonicalPi y gU_11 gU_22))  (TermLam x et) )   (TermEp (EvidenceEv gU_33) rv) ) (TermEp (EvidenceEv gU_22^)   (esubst  et   x   (TermEp (EvidenceEv gU_11^) rv)   gu   gU_11^ )  ))]

;; #source file ./ott/lang_simple.ott  lines 3140 - 3145 
 [
  
  (GNCheck EnvEmpty gu rv gU_11)
  (GHsub y gU_11 gu gU_22 gU_22^)
  --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- "StepAppEvRaw"
  (Step (TermApp  (TermEp (EvidenceEv (CanonicalPi y gU_11 gU_22))  (TermLam x et) )  rv) (TermEp (EvidenceEv gU_22^)   (esubst  et   x    (TermEp (EvidenceEv gU_11) rv)    gu   gU_11 )  ))]

;; #source file ./ott/lang_simple.ott  lines 3149 - 3153 
 [
  (GNCheck EnvEmpty gu ev gU_11)
  (GHsub x gU_11 gu gU_22 gU_22^)
  ---------------------------------------------------------------------------------------------------------------------- "StepAppDyn"
  (Step (TermApp  (TermEp (EvidenceEv (CanonicalPi x gU_11 gU_22)) TermDyn)  ev) (TermEp (EvidenceEv gU_22^) TermDyn))]

;; #source file ./ott/lang_simple.ott  lines 3155 - 3158 

;; #source file ./ott/lang_simple.ott  lines 3180 - 3184 

;; #source file ./ott/lang_simple.ott  lines 3185 - 3188 
)
;; #source file ./ott/lang_simple.ott  lines 3264 - 3287 

;;;;;;;;;;;;;;;;;;;;;
;; A judgment form to get both the elaborated evidence term
;; and normal form for a term
;; and wrap them up with their type in a tuple
;;;;;;;;;;;;;;;;;;;;;

(define-judgment-form
  L
  #:mode (ElabNormType I I O)
  [ 
  (GradualNESynth Gamma gt et gu gU)
  (where et_subbed ,(perform-elab-substs (term et)))
  ---------------------------------
  (ElabNormType Gamma gt (ENTTriple et_subbed gu gU))]

)

