;; #source  
;;; generated by Ott 0.28 from: ./ott/lang_simple.ott

#lang racket
(require redex/reduction-semantics)

;; #source file ./ott/lang_simple.ott  lines 4 - 6 
;; #source file ./ott/lang_simple.ott  lines 8 - 13 
(provide (all-defined-out))

(define currently-defined-vars 
  (make-hasheq))

;; #source file ./ott/lang_simple.ott  lines 15 - 91 
;; #source file ./ott/lang_simple.ott  lines 96 - 98 
;; #source file ./ott/lang_simple.ott  lines 101 - 101 
;; #source file ./ott/lang_simple.ott  lines 107 - 115 and file ./ott/lang_simple.ott  lines 120 - 127 and file ./ott/lang_simple.ott  lines 131 - 165 and file ./ott/lang_simple.ott  lines 170 - 179 and file ./ott/lang_simple.ott  lines 188 - 193 and file ./ott/lang_simple.ott  lines 196 - 201 and file ./ott/lang_simple.ott  lines 203 - 205 and file ./ott/lang_simple.ott  lines 208 - 214 and file ./ott/lang_simple.ott  lines 217 - 219 and file ./ott/lang_simple.ott  lines 221 - 251 and file ./ott/lang_simple.ott  lines 256 - 271 and file ./ott/lang_simple.ott  lines 274 - 279 and file ./ott/lang_simple.ott  lines 281 - 284 and file ./ott/lang_simple.ott  lines 292 - 294 and file ./ott/lang_simple.ott  lines 302 - 313 and file ./ott/lang_simple.ott  lines 317 - 323 and file ./ott/lang_simple.ott  lines 326 - 331 and file ./ott/lang_simple.ott  lines 333 - 341 and file ./ott/lang_simple.ott  lines 345 - 347 and file ./ott/lang_simple.ott  lines 358 - 363 and file ./ott/lang_simple.ott  lines 365 - 371 and file ./ott/lang_simple.ott  lines 417 - 420 and file ./ott/lang_simple.ott  lines 422 - 426 and file ./ott/lang_simple.ott  lines 428 - 432 and file ./ott/lang_simple.ott  lines 555 - 560 and file ./ott/lang_simple.ott  lines 563 - 565 and file ./ott/lang_simple.ott  lines 567 - 569 and file ./ott/lang_simple.ott  lines 571 - 572 
(define-language L  

(level i j ::= natural)

;; #source file ./ott/lang_simple.ott  lines 256 - 271 
  (canonical gu gU ::= 
    (CanonicalLam var gu)
    (CanonicalAtomic grr)
    CanonicalDyn
    (CanonicalPi var gU_11 gU_22))
  ;grammar_pp, 2817: and 
;; #source file ./ott/lang_simple.ott  lines 274 - 279 
  (atomic grr gRR ::= 
    (AtomicSpine var ge)
    (AtomicSet i))
  ;grammar_pp, 2817: and 
;; #source file ./ott/lang_simple.ott  lines 281 - 284 
  (spine ge ::= 
    SpineEmpty
    (SpineCons ge gu))

;; #source file ./ott/lang_simple.ott  lines 428 - 432 
  (Env ::= 
    EnvEmpty
    (EnvExt var gU Env)
    (Envconcat Env_11 Env_22))

;; #source file ./ott/lang_simple.ott  lines 292 - 294 
  (epsilon ep ::= 
    (EvidenceEv Gamma gU))

;; #source file ./ott/lang_simple.ott  lines 131 - 165 
  (term tt ett TT ::= 
    (TermLam var tt)
    (TermApp tt_11 tt_22)
    var
    (TermSet i)
    (TermPi var TT_11 TT_22)
    (TermAnn tt TT)
    (TermEp ep tt)
    TermDyn
    TermError)

(iinf ::= number)

;; #source file ./ott/lang_simple.ott  lines 358 - 363 
  (simpleContext SC ::= 
    (TermApp hole t)
    (TermApp sv hole)
    (TermPi x hole T)
    (TermAnn hole T))

;; #source file ./ott/lang_simple.ott  lines 571 - 572 
  (ent ::= 
    (ENTTriple et gu gU))

;; #source file ./ott/lang_simple.ott  lines 567 - 569 
  (iinfs jinfs ::= 
    (UniverseMultiSetSingleton iinf)
    (UniverseMultiSetSum iinfs jinfs))

;; #source file ./ott/lang_simple.ott  lines 563 - 565 
  (is js ::= 
    (LevelMultiSetSingleton i)
    (LevelMultiSetSum is js))

;; #source file ./ott/lang_simple.ott  lines 345 - 347 
  (dummyev dummyeV ::= 
    (DummyEvidenceValueEv ep rv)
    (DummyEvidenceValueRaw rv))

;; #source file ./ott/lang_simple.ott  lines 365 - 371 
  (evalContext EC ::= 
    (TermApp hole et)
    (TermApp ev hole)
    (TermPi x hole eT)
    (TermEp ep hole))

;; #source file ./ott/lang_simple.ott  lines 120 - 127 
  (ttSynth ettSynth TTSynth ::= 
    (TermApp tt_11 tt_22)
    var
    (TermSet i)
    (TermAnn tt TT)
    TermDyn)

;; #source file ./ott/lang_simple.ott  lines 196 - 201 
  (rr RR ::= 
    (AtomicSpine var e)
    (AtomicSet i))

;; #source file ./ott/lang_simple.ott  lines 417 - 420 
  (SGamma ::= 
    EnvEmpty
    (EnvExt var U SGamma)
    (Envconcat SGamma_11 SGamma_22))

;; #source file ./ott/lang_simple.ott  lines 326 - 331 
  (simpleValue sv sV ::= 
    (TermLam var t)
    (TermPi var sV T)
    (TermSet i))

;; #source file ./ott/lang_simple.ott  lines 217 - 219 
  (gtCheckOnly gTCheckOnly ::= 
    (TermLam var gt)
    (TermPi var gT_11 gT_22))

;; #source file ./ott/lang_simple.ott  lines 188 - 193 
  (u U ::= 
    (CanonicalLam var u)
    (CanonicalAtomic rr)
    (CanonicalPi var U_11 U_22))

;; #source file ./ott/lang_simple.ott  lines 203 - 205 
  (e ::= 
    SpineEmpty
    (SpineCons e u))

;; #source file ./ott/lang_simple.ott  lines 317 - 323 
  (rv rV ::= 
    (TermLam var et)
    (TermPi var eV eT)
    (TermSet i)
    TermDyn)

;; #source file ./ott/lang_simple.ott  lines 422 - 426 
  (Gamma ::= 
    EnvEmpty
    (EnvExt var gU Gamma)
    (Envconcat Gamma_11 Gamma_22))

;; #source file ./ott/lang_simple.ott  lines 170 - 179 
  (t T ::= 
    (TermLam var t)
    (TermApp t_11 t_22)
    var
    (TermPi var T_11 T_22)
    (TermSet i)
    (TermAnn t T))

;; #source file ./ott/lang_simple.ott  lines 208 - 214 
  (gtSynth gTSynth ::= 
    (TermApp gt_11 gt_22)
    var
    (TermSet i)
    (TermAnn gt gT)
    TermDyn)

;; #source file ./ott/lang_simple.ott  lines 302 - 313 
  (et eT ::= 
    (TermLam var et)
    (TermApp et_11 et_22)
    var
    (TermPi var eT_11 eT_22)
    (TermSet i)
    TermDyn
    (TermEp ep et)
    TermError)

;; #source file ./ott/lang_simple.ott  lines 221 - 251 
  (gt gT ::= 
    (TermLam var gt)
    (TermApp gt_11 gt_22)
    var
    (TermSet i)
    (TermPi var gT_11 gT_22)
    (TermAnn gt gT)
    TermDyn)

;; #source file ./ott/lang_simple.ott  lines 333 - 341 
  (ev eV ::= 
    (TermEp ep rv)
    (TermPi var eV eT)
    (TermLam var et)
    (TermSet i)
    TermDyn)
   (var x y z X Y Z ::= variable-not-otherwise-mentioned)

    #:binding-forms

    (TermLam x tt #:refers-to (shadow x))
    (TermPi x TT_11 TT_22 #:refers-to (shadow x))
    (StaticTermLam x t #:refers-to (shadow x))
    (StaticTermPi x T_11 T_22)
    (SCanonicalLam x u #:refers-to (shadow x))

    (GradualTermCheckOnlyLam x gt #:refers-to (shadow x))
    (GradualTermCheckOnlyPi x gT_11 gT_22 #:refers-to (shadow x))
    (GradualTermLam x gt #:refers-to (shadow x))
    (GradualTermPi x gT_11 gT_22 #:refers-to (shadow x))
    (CanonicalLam x gu #:refers-to (shadow x))
    (CanonicalPi x gU_11 gU_22 #:refers-to (shadow x))

    (EvidenceTermLam x et #:refers-to (shadow x))
    (EvidenceTermPi x eT_11 eT_22 #:refers-to (shadow x))
    (RawValueLam x et #:refers-to (shadow x))
    (SimpleValueLam x t #:refers-to (shadow x))
    (SimpleValuePi x sV T #:refers-to (shadow x))
    (EvidenceValuePi x eV eT #:refers-to (shadow x))
    (EvidenceValueLam x et #:refers-to (shadow x))

)

;;;; subrules 
;; #source file ./ott/lang_simple.ott  lines 586 - 586 and file ./ott/lang_simple.ott  lines 587 - 587 and file ./ott/lang_simple.ott  lines 590 - 590 and file ./ott/lang_simple.ott  lines 591 - 591 and file ./ott/lang_simple.ott  lines 592 - 592 and file ./ott/lang_simple.ott  lines 593 - 593 and file ./ott/lang_simple.ott  lines 594 - 594 and file ./ott/lang_simple.ott  lines 595 - 595 and file ./ott/lang_simple.ott  lines 596 - 596 and file ./ott/lang_simple.ott  lines 597 - 597 and file ./ott/lang_simple.ott  lines 599 - 599 and file ./ott/lang_simple.ott  lines 600 - 600 and file ./ott/lang_simple.ott  lines 605 - 605 and file ./ott/lang_simple.ott  lines 606 - 606 and file ./ott/lang_simple.ott  lines 607 - 607 and file ./ott/lang_simple.ott  lines 610 - 610 
;; #source file ./ott/lang_simple.ott  lines 621 - 632 
;; #source file ./ott/lang_simple.ott  lines 634 - 741 

(define-metafunction L 
  succ : i -> i
  [(succ i) ,(+ (term i) 1)])
  
  (define-metafunction L 
  pred : i -> i
  [(pred i) ,(- (term i) 1)])

(define-metafunction L 
  esubst : et var et -> et 
  [(esubst x_old x_old et_new) et_new ]
  [(esubst x_old y et_new) y ]
  [(esubst (TermPi y eS eT) x_old et_new) 
    (TermPi z (esubst eS x_old et_new) (esubst (substitute eT x z) x_old et_new ))
    (where   z  ,(gensym)) ] 
  [(esubst (TermLam y et) x_old et_new) 
    (TermLam z (esubst (substitute et x z) x_old et_new ))
    (where   z  ,(gensym)) ]
  [(esubst (TermApp et_1 et_2) x_old et_new) (TermApp (esubst et_1 x_old et_new) (esubst et_2 x_old et_new))]
  [(esubst (TermEp (EvidenceEv Gamma gU_1 ) et) x_old et_new) (TermEp (EvidenceEv Gamma_1 gU_2) (esubst et x_old et_new))
    (judgment-holds (GVarLook x_old gU_V Gamma))
    (judgment-holds (GNCheck Gamma gu_esnorm et gU_V))
    (judgment-holds (GradualEnvSub Gamma x_old gU_V gu_esnorm Gamma_1))
    (judgment-holds (GHsub  x_old gU_V gu_esnorm gU_1 gU_2))]
  ;; TODO get rid of types on ? or add Gamma
  [(esubst et x_old et_new) et] 
)

(define-metafunction L 
 is-check-only : term -> boolean
 [(is-check-only TermDyn) #t]
 [(is-check-only (TermPi x TT_1 TT_2)) #t]
 [(is-check-only (TermLam x tt)) #t]
 [(is-check-only tt) #f] 
)

(define-metafunction L 
 is-check-pair : term gU -> boolean
 [(is-check-pair TermDyn gU) #t]
 [(is-check-pair (TermPi x TT_1 TT_2) (CanonicalAtomic (AtomicDyn))) #t]
 [(is-check-pair (TermPi x TT_1 TT_2) (CanonicalAtomic (AtomicSet i))) #t]
 [(is-check-pair (TermLam x tt) (CanonicalAtomic (AtomicDyn))) #t]
 [(is-check-pair (TermLam x tt) (CanonicalPi y gU gU_V)) #t]
 [(is-check-pair tt gU) #f] 
)

(define-metafunction L 
 is-set-pair : gU gU_V -> boolean
 [(is-set-pair (CanonicalAtomic (AtomicSet i)) (CanonicalAtomic (AtomicSet j))) #t (side-condition (< (term i) (term j)))]
 [(is-set-pair gU gU_V) #f] 
)

(define-metafunction L 
 type-in-ev : ep -> gU
 [(type-in-ev (EvidenceEv Gamma gU)) gU]
)

(define (pt tm)
  (with-handlers ([exn:fail:redex?
                   (lambda (exn) (format "~a" tm))])
    (pretty-term tm)
    ))

(define pretty-term
    (term-match/single L
    [x (symbol->string (term x))]
    [(TermLam x tt) (string-append "(λ " (pt (term x)) " . " (pt (term tt)) ")")]
    [(TermPi x TT_1 TT_2) (string-append "(( " (pt (term x)) " : " (pt (term TT_1)) ") -> " (pt (term TT_2)) ")")]
    [(TermSet i) (string-append "Set" (number->string (term i)))]
    [(TermApp tt_1 tt_2) (string-append "(" (pt (term tt_1)) " " (pt (term tt_2)) ")")]
    [TermDyn "?"]
    [TermError "⊥"]
    [(TermAnn tt_1 tt_2) (string-append (pt (term tt_1)) " :: " (pt (term tt_2)))]
    [(TermDynAnn gU) (string-append "?" (pt (term gU)))]
    [(TermEp (EvidenceEv Gamma gU ) tt) (string-append "〈" (pt (term gU)) "〉" (pt (term tt)))]
    [(CanonicalAtomic grr) (pt (term grr))]
    [(CanonicalLam x gu) (string-append "(λ " (pt (term x)) " . " (pt (term gu)) ")")]
    [(CanonicalPi x gU gU_V) (string-append "(( " (pt (term x)) " : " (pt (term gU)) ") -> " (pt (term gU_V)) ")")]
    [(AtomicSet i) (string-append "Set" (number->string (term i)))]
    [CanonicalDyn "?"]
    [(AtomicSpine x ge) (string-append "(" (pt (term x)) " " (pt (term ge)) ")")]
    [SpineEmpty ""]
    [(SpineCons ge gu) (string-append (pt (term ge)) " " (pt (term gu)))]
    
    ))

(define (printEvType ep)
 (term-let ([(EvidenceEv Gamma gU ) ep]) (pt (term gU))))

(define-extended-language LContext
  L
  (redexContext RC ::= 
    hole
    (TermApp RC et)
    (TermApp ev RC)
    (TermPi x RC eT)
    (TermEp ep RC))
)

(define Red
  (reduction-relation LContext
  (--> et_1 et_2 (judgment-holds (Step et_1 et_2)))
  )
)

 

;;; definitions 

(define-judgment-form
  L
  #:mode (GVarLook I O I)
  #:contract (GVarLook x gU Gamma)

;; #source file ./ott/lang_simple.ott  lines 750 - 752 
 [
  ------------------------------------- "GVarLookHead"
  (GVarLook x gU (EnvExt x gU Gamma))]

;; #source file ./ott/lang_simple.ott  lines 753 - 757 
 [
   (side-condition ,(not (alpha-equivalent? L (term  (CanonicalAtomic  (AtomicSpine  x  SpineEmpty) ) ) (term  (CanonicalAtomic  (AtomicSpine  y  SpineEmpty) ) )))) 
  (GVarLook x gU_11 Gamma)
  ------------------------------------------- "GVarLookTail"
  (GVarLook x gU_11 (EnvExt y gU_22 Gamma))]

)
(define-judgment-form L 
 
  #:mode (GVarFree I I)
  #:contract (GVarFree x Gamma)

;; #source file ./ott/lang_simple.ott  lines 761 - 763 
 [----------------------- "GFreeLookNil"
  (GVarFree x EnvEmpty)]

;; #source file ./ott/lang_simple.ott  lines 764 - 768 
 [
   (side-condition ,(not (alpha-equivalent? L (term  (CanonicalAtomic  (AtomicSpine  x  SpineEmpty) ) ) (term  (CanonicalAtomic  (AtomicSpine  y  SpineEmpty) ) )))) 
  (GVarFree x Gamma)
  ---------------------------------- "GFreeLookCons"
  (GVarFree x (EnvExt y gU Gamma))]
)

;;; definitions 

(define-judgment-form
  L
  #:mode (Universe I I O)
  #:contract (Universe Gamma gu iinf)

;; #source file ./ott/lang_simple.ott  lines 789 - 792 
 [
   (side-condition ,(> (term  i ) 0)) 
  ----------------------------------------------------------------- "UniverseSet"
  (Universe Gamma (CanonicalAtomic (AtomicSet i))   (succ  i )  )]

;; #source file ./ott/lang_simple.ott  lines 793 - 798 
 [
  (GVarLook x gU Gamma)
  (Universe Gamma gU  i )
   (side-condition ,(> (term  i ) 0)) 
  ---------------------------------------------------------------------------------- "UniverseVar"
  (Universe Gamma (CanonicalAtomic  (AtomicSpine  x  SpineEmpty) )   (pred  i )  )]

;; #source file ./ott/lang_simple.ott  lines 799 - 803 
 [
  (Universe Gamma gU_11  i )
  (Universe (EnvExt x gU_11 Gamma) gU_22  j )
  ------------------------------------------------------------------ "UniversePi"
  (Universe Gamma (CanonicalPi x gU_11 gU_22)  (max   i     j  ) )]

;; #source file ./ott/lang_simple.ott  lines 804 - 807 
 [
  (Universe Gamma gu  i )
  -------------------------------------------- "UniverseLam"
  (Universe Gamma  (CanonicalLam x gu)   i )]

;; #source file ./ott/lang_simple.ott  lines 808 - 812 
 [
  (Universe Gamma (CanonicalAtomic (AtomicSpine x ge))  i )
  (Universe Gamma gu  j )
  ------------------------------------------------------------------------------------------ "UniverseSpine"
  (Universe Gamma (CanonicalAtomic (AtomicSpine x (SpineCons ge gu)))  (max   i     j  ) )]

;; #source file ./ott/lang_simple.ott  lines 813 - 815 
 [
  ---------------------------------------- "UniverseDyn"
  (Universe Gamma CanonicalDyn  +inf.0 )]

)
(define-judgment-form L 
 
  #:mode (SUniverse I I O)
  #:contract (SUniverse SGamma u i)

;; #source file ./ott/lang_simple.ott  lines 821 - 824 
 [
   (side-condition ,(> (term  i ) 0)) 
  ----------------------------------------------------------------- "SUniverseSet"
  (SUniverse SGamma (CanonicalAtomic (AtomicSet i))  (succ  i ) )]

;; #source file ./ott/lang_simple.ott  lines 825 - 830 
 [
  (GVarLook x U SGamma)
  (SUniverse SGamma U i)
   (side-condition ,(> (term  i ) 0)) 
  ---------------------------------------------------------------------------------- "SUniverseVar"
  (SUniverse SGamma (CanonicalAtomic  (AtomicSpine  x  SpineEmpty) )  (pred  i ) )]

;; #source file ./ott/lang_simple.ott  lines 832 - 836 
 [
  (SUniverse SGamma U_11 i)
  (SUniverse (EnvExt x U_11 SGamma) U_22 j)
  -------------------------------------------------------------- "SUniversePi"
  (SUniverse SGamma (CanonicalPi x U_11 U_22)  (max  i   j ) )]

;; #source file ./ott/lang_simple.ott  lines 837 - 839 
 [
  
  --------------------------------------------- "SUniverseLam"
  (SUniverse SGamma  (CanonicalLam x u)   0 )]

;; #source file ./ott/lang_simple.ott  lines 840 - 844 
 [
  
  (SUniverse SGamma (CanonicalAtomic (AtomicSpine x e)) i)
  (SUniverse SGamma u j)
  -------------------------------------------------------------------------------------- "SUniverseSpine"
  (SUniverse SGamma (CanonicalAtomic (AtomicSpine x (SpineCons e u)))  (max  i   j ) )]
)

;;; definitions 

(define-judgment-form
  L
  #:mode (SHsub I I I I O)
  #:contract (SHsub x U u_11 u_22 u_33)

;; #source file ./ott/lang_simple.ott  lines 865 - 870 
 [
  (SHsub x U u U_11 U_11^)
  (SHsub x U u U_22 U_22^)
   (side-condition ,(not (alpha-equivalent? L (term  (CanonicalAtomic  (AtomicSpine  x  SpineEmpty) ) ) (term  (CanonicalAtomic  (AtomicSpine  y  SpineEmpty) ) )))) 
  --------------------------------------------------------------------- "SHsubPi"
  (SHsub x U u (CanonicalPi y U_11 U_22) (CanonicalPi y U_11^ U_22^))]

;; #source file ./ott/lang_simple.ott  lines 872 - 875 
 [
   (side-condition ,(not (alpha-equivalent? L (term  (CanonicalAtomic  (AtomicSpine  x  SpineEmpty) ) ) (term  (CanonicalAtomic  (AtomicSpine  y  SpineEmpty) ) )))) 
  ----------------------------------------------------------------------------------------------------------------- "SHsubDiffNil"
  (SHsub x U u (CanonicalAtomic  (AtomicSpine  y  SpineEmpty) ) (CanonicalAtomic  (AtomicSpine  y  SpineEmpty) ))]

;; #source file ./ott/lang_simple.ott  lines 876 - 881 
 [
  
   (side-condition ,(not (alpha-equivalent? L (term  (CanonicalAtomic  (AtomicSpine  x  SpineEmpty) ) ) (term  (CanonicalAtomic  (AtomicSpine  y  SpineEmpty) ) )))) 
  (SHsub x U u (CanonicalAtomic (AtomicSpine y e)) (CanonicalAtomic (AtomicSpine y e_^)))
  (SHsub x U u u_22 u_33)
  --------------------------------------------------------------------------------------------------------------------------- "SHsubDiffCons"
  (SHsub x U u (CanonicalAtomic (AtomicSpine y (SpineCons e u_22))) (CanonicalAtomic (AtomicSpine y (SpineCons e_^ u_33))))]

;; #source file ./ott/lang_simple.ott  lines 884 - 886 
 [
  ------------------------------------------------------------------------------- "SHsubSet"
  (SHsub x U u (CanonicalAtomic (AtomicSet i)) (CanonicalAtomic (AtomicSet i)))]

;; #source file ./ott/lang_simple.ott  lines 888 - 892 
 [
  
  (SHsub x U u u_22 u_33)
   (side-condition ,(not (alpha-equivalent? L (term  (CanonicalAtomic  (AtomicSpine  x  SpineEmpty) ) ) (term  (CanonicalAtomic  (AtomicSpine  y  SpineEmpty) ) )))) 
  --------------------------------------------------------------- "SHsubLam"
  (SHsub x U u  (CanonicalLam y u_22)   (CanonicalLam y u_33) )]

;; #source file ./ott/lang_simple.ott  lines 897 - 900 
 [
  
  (SHsubR x U u_11 (SpineCons e u_22) u_33 U_^)
  ---------------------------------------------------------------------------- "SHsubSpine"
  (SHsub x U u_11 (CanonicalAtomic (AtomicSpine x (SpineCons e u_22))) u_33)]

)
(define-judgment-form L 
 
  #:mode (SHsubR I I I I O O)
  #:contract (SHsubR x U u e u_^ U_^)

;; #source file ./ott/lang_simple.ott  lines 911 - 913 
 [
  ------------------------------- "SHsubRHead"
  (SHsubR x U u SpineEmpty u U)]

;; #source file ./ott/lang_simple.ott  lines 914 - 921 
 [
  
   (SHsubR x U u_11 e  (CanonicalLam y u_11^)  (CanonicalPi y U_11^ U_22^))   (SHsub x U u_11 u_22 u_33) 
   (SHsub y U_11^ u_33 u_11^ u_22^)   (SHsub y U_11^ u_33 U_22^ U_33^) 
  -------------------------------------------------- "SHsubRSpine"
  (SHsubR x U u_11 (SpineCons e u_22) u_22^ U_33^)]
)

;;; definitions 

(define-judgment-form
  L
  #:mode (SWF I)
  #:contract (SWF SGamma)

;; #source file ./ott/lang_simple.ott  lines 931 - 933 
 [---------------- "SWFEmpty"
  (SWF EnvEmpty)]

;; #source file ./ott/lang_simple.ott  lines 934 - 937 
 [
    (SWF SGamma)   (StaticSet SGamma U)    (GVarFree x SGamma) 
  --------------------------- "SWFExt"
  (SWF (EnvExt x U SGamma))]

)
(define-judgment-form L 
 
  #:mode (StaticSet I I)
  #:contract (StaticSet SGamma U)

;; #source file ./ott/lang_simple.ott  lines 948 - 951 
 [
  
  (SCSynth SGamma rr (CanonicalAtomic (AtomicSet i)))
  ----------------------------------------- "StaticSetSet"
  (StaticSet SGamma (CanonicalAtomic rr))]

;; #source file ./ott/lang_simple.ott  lines 954 - 959 
 [
  (StaticSet SGamma U_11)
  (SWF (EnvExt x U_11 SGamma))
  (StaticSet (EnvExt x U_11 SGamma) U_22)
  ---------------------------------------------- "StaticSetPi"
  (StaticSet SGamma (CanonicalPi x U_11 U_22))]

)
(define-judgment-form L 
 
  #:mode (SCSynth I I O)
  #:contract (SCSynth SGamma rr U)

;; #source file ./ott/lang_simple.ott  lines 967 - 970 
 [
   (side-condition ,(> (term  i ) 0)) 
  ---------------------------------------------------------------------------- "SCSynthSet"
  (SCSynth SGamma (AtomicSet i) (CanonicalAtomic  (AtomicSet (succ  i ) ) ))]

;; #source file ./ott/lang_simple.ott  lines 972 - 976 
 [
  
  (SWF SGamma)
  (GVarLook x U SGamma)
  --------------------------------------------------- "SCSynthVar"
  (SCSynth SGamma  (AtomicSpine  x  SpineEmpty)  U)]

;; #source file ./ott/lang_simple.ott  lines 980 - 984 
 [
  
  (SCSynth SGamma (AtomicSpine x e) (CanonicalPi y U_11 U_22))
   (SCCheck SGamma u U_11)   (SHsub y U_11 u U_22 U_33) 
  ------------------------------------------------------- "SCSynthApp"
  (SCSynth SGamma (AtomicSpine x (SpineCons e u)) U_33)]

)
(define-judgment-form L 
 
  #:mode (SCCheck I I I)
  #:contract (SCCheck SGamma u U)

;; #source file ./ott/lang_simple.ott  lines 992 - 995 
 [
  
  (SCSynth SGamma rr (CanonicalAtomic RR))
  ------------------------------------------------------------ "SCCheckSynth"
  (SCCheck SGamma (CanonicalAtomic rr) (CanonicalAtomic RR))]

;; #source file ./ott/lang_simple.ott  lines 996 - 1000 
 [
  (SCSynth SGamma RR (CanonicalAtomic (AtomicSet i)))
   (side-condition ,(and (< 0 (term  i )) (< (term  i ) (term  j )))) 
  ----------------------------------------------------------------------- "SCCheckLevel"
  (SCCheck SGamma (CanonicalAtomic RR) (CanonicalAtomic (AtomicSet j)))]

;; #source file ./ott/lang_simple.ott  lines 1002 - 1005 
 [
  
   (SWF (EnvExt x U_11 SGamma))   (SCCheck (EnvExt x U_11 SGamma) u U_22) 
  ----------------------------------------------------------------- "SCCheckLam"
  (SCCheck SGamma  (CanonicalLam x u)  (CanonicalPi x U_11 U_22))]

;; #source file ./ott/lang_simple.ott  lines 1006 - 1010 
 [
  (SCCheck SGamma U_11 (CanonicalAtomic (AtomicSet i)))
   (SWF (EnvExt x U_11 SGamma))   (SCCheck (EnvExt x U_11 SGamma) U_22 (CanonicalAtomic (AtomicSet i))) 
  ---------------------------------------------------------------------------- "SCCheckPi"
  (SCCheck SGamma (CanonicalPi x U_11 U_22) (CanonicalAtomic (AtomicSet i)))]
)

;;; definitions 

(define-judgment-form
  L
  #:mode (SSynth I I O)
  #:contract (SSynth SGamma t U)

;; #source file ./ott/lang_simple.ott  lines 1020 - 1024 
 [
  
  (StaticSetNorm SGamma U T)
  (SCheck SGamma t U)
  ----------------------------------- "SSynthAnn"
  (SSynth SGamma  (TermAnn t T)  U)]

;; #source file ./ott/lang_simple.ott  lines 1025 - 1028 
 [
   (side-condition ,(> (term  i ) 0)) 
  ------------------------------------------------------------------------- "SSynthSet"
  (SSynth SGamma (TermSet i) (CanonicalAtomic  (AtomicSet (succ  i ) ) ))]

;; #source file ./ott/lang_simple.ott  lines 1030 - 1034 
 [
  
  (SWF SGamma)
  (GVarLook x U SGamma)
  ------------------------------- "SSynthVar"
  (SSynth SGamma x U)]

;; #source file ./ott/lang_simple.ott  lines 1039 - 1043 
 [
  
   (SSynth SGamma t_11 (CanonicalPi x U_11 U_22))   (SNormCheck SGamma u t_22 U_11) 
  (SHsub x U_11 u U_22 U_33)
  ------------------------------------------ "SSynthApp"
  (SSynth SGamma (TermApp t_11 t_22) U_33)]

)
(define-judgment-form L 
 
  #:mode (SCheck I I I)
  #:contract (SCheck SGamma t U)

;; #source file ./ott/lang_simple.ott  lines 1050 - 1053 
 [
  
  (SSynth SGamma t U)
  --------------------- "SCheckSynth"
  (SCheck SGamma t U)]

;; #source file ./ott/lang_simple.ott  lines 1054 - 1058 
 [
  (SSynth SGamma T (CanonicalAtomic (AtomicSet i)))
   (side-condition ,(and (< 0 (term  i )) (< (term  i ) (term  j )))) 
  --------------------------------------------------- "SCheckLevel"
  (SCheck SGamma T (CanonicalAtomic (AtomicSet j)))]

;; #source file ./ott/lang_simple.ott  lines 1059 - 1062 
 [
    (SNormCheck SGamma U T_11 (CanonicalAtomic (AtomicSet i)))   (SWF (EnvExt x U SGamma))    (SCheck (EnvExt x U SGamma) T_22 (CanonicalAtomic (AtomicSet i))) 
  ---------------------------------------------------------------------- "SCheckPi"
  (SCheck SGamma (TermPi x T_11 T_22) (CanonicalAtomic (AtomicSet i)))]

;; #source file ./ott/lang_simple.ott  lines 1064 - 1068 
 [
  
  (SWF (EnvExt x U_11 SGamma))
  (SCheck (EnvExt x U_11 SGamma) t U_22)
  ----------------------------------------------------------- "SCheckLam"
  (SCheck SGamma  (TermLam x t)  (CanonicalPi x U_11 U_22))]

)
(define-judgment-form L 
 
  #:mode (StaticSetNorm I O I)
  #:contract (StaticSetNorm SGamma U T)

;; #source file ./ott/lang_simple.ott  lines 1081 - 1084 
 [
  (SNormSynth SGamma T U (CanonicalAtomic (AtomicSet i)))
  ---------------------------- "StaticSetNormSynth"
  (StaticSetNorm SGamma U T)]

;; #source file ./ott/lang_simple.ott  lines 1085 - 1089 
 [
  (StaticSetNorm SGamma U_11 T_11)
  (StaticSetNorm (EnvExt x U_11 SGamma) U_22 T_22)
  ----------------------------------------------------------------------- "StaticSetNormPi"
  (StaticSetNorm SGamma (CanonicalPi x U_11 U_22) (TermPi x T_11 T_22))]

)
(define-judgment-form L 
 
  #:mode (SNormSynth I I O O)
  #:contract (SNormSynth SGamma t u U)

;; #source file ./ott/lang_simple.ott  lines 1095 - 1099 
 [
  
  (StaticSetNorm SGamma U T)
  (SNormCheck SGamma u t U)
  ----------------------------------------- "SNormSynthAnn"
  (SNormSynth SGamma  (TermAnn t T)  u U)]

;; #source file ./ott/lang_simple.ott  lines 1100 - 1103 
 [
   (side-condition ,(> (term  i ) 0)) 
  ------------------------------------------------------------------------------------------------------------- "SNormSynthSet"
  (SNormSynth SGamma (TermSet i) (CanonicalAtomic (AtomicSet i)) (CanonicalAtomic  (AtomicSet (succ  i ) ) ))]

;; #source file ./ott/lang_simple.ott  lines 1105 - 1110 
 [
  
  (SWF SGamma)
  (GVarLook x U SGamma)
  (EtaExpand  (AtomicSpine  x  SpineEmpty)  u U)
  ------------------------------------- "SNormSynthVar"
  (SNormSynth SGamma x u U)]

;; #source file ./ott/lang_simple.ott  lines 1115 - 1120 
 [
  
  (SNormSynth SGamma t_11  (CanonicalLam x u_11)  (CanonicalPi x U_11 U_22))
  (SNormCheck SGamma u_22 t_22 U_11)
   (SHsub x U_11 u_22 u_11 u_33)   (SHsub x U_11 u_22 U_22 U_33) 
  --------------------------------------------------- "SNormSynthApp"
  (SNormSynth SGamma (TermApp t_11 t_22) u_33 U_33)]

)
(define-judgment-form L 
 
  #:mode (SNormCheck I O I I)
  #:contract (SNormCheck SGamma u t U)

;; #source file ./ott/lang_simple.ott  lines 1129 - 1132 
 [
  
  (SNormSynth SGamma t u U)
  --------------------------- "SNormCheckSynth"
  (SNormCheck SGamma u t U)]

;; #source file ./ott/lang_simple.ott  lines 1133 - 1137 
 [
  (SNormSynth SGamma T U (CanonicalAtomic (AtomicSet i)))
   (side-condition ,(and (< 0 (term  i )) (< (term  i ) (term  j )))) 
  --------------------------------------------------------- "SNormCheckLevel"
  (SNormCheck SGamma U T (CanonicalAtomic (AtomicSet j)))]

;; #source file ./ott/lang_simple.ott  lines 1139 - 1144 
 [
  (SNormCheck SGamma U_11 T_11 (CanonicalAtomic (AtomicSet i)))
  (SWF (EnvExt x U_11 SGamma))
  (SNormCheck (EnvExt x U_11 SGamma) U_22 T_22 (CanonicalAtomic (AtomicSet i)))
  ---------------------------------------------------------------------------------------------------- "SNormCheckPi"
  (SNormCheck SGamma (CanonicalPi x U_11 U_22) (TermPi x T_11 T_22) (CanonicalAtomic (AtomicSet i)))]

;; #source file ./ott/lang_simple.ott  lines 1145 - 1149 
 [
  
  (SWF (EnvExt x U_11 SGamma))
  (SNormCheck (EnvExt x U_11 SGamma) u t U_22)
  ------------------------------------------------------------------------------------ "SNormCheckLam"
  (SNormCheck SGamma  (CanonicalLam x u)   (TermLam x t)  (CanonicalPi x U_11 U_22))]

)
(define-judgment-form L 
 
  #:mode (EtaExpand I O I)
  #:contract (EtaExpand rr u U)

;; #source file ./ott/lang_simple.ott  lines 1154 - 1156 
 [
  ---------------------------------------------------------- "EtaExpandAtomic"
  (EtaExpand rr (CanonicalAtomic rr) (CanonicalAtomic RR))]

;; #source file ./ott/lang_simple.ott  lines 1158 - 1161 
 [
  
   (EtaExpand  (AtomicSpine  y  SpineEmpty)  u U_11)   (EtaExpand (AtomicSpine x (SpineCons e u)) u U_22) 
  ------------------------------------------------------------------------------ "EtaExpandPi"
  (EtaExpand (AtomicSpine x e)  (CanonicalLam y u)  (CanonicalPi y U_11 U_22))]
)

;;; definitions 

(define-judgment-form
  L
  #:mode (Domain I O)
  #:contract (Domain gU_11 gU_22)

;; #source file ./ott/lang_simple.ott  lines 1179 - 1181 
 [-------------------------------------------- "DomainPi"
  (Domain (CanonicalPi x gU_11 gU_22) gU_11)]

;; #source file ./ott/lang_simple.ott  lines 1182 - 1184 
 [------------------------------------ "DomainDyn"
  (Domain CanonicalDyn CanonicalDyn)]

)
(define-judgment-form L 
 
  #:mode (GradualEnvSub I I I I O)
  #:contract (GradualEnvSub x gU gu Gamma Gamma_^)

;; #source file ./ott/lang_simple.ott  lines 1202 - 1204 
 [------------------------------------------- "GradualEnvSubEmpty"
  (GradualEnvSub x gU gu EnvEmpty EnvEmpty)]

;; #source file ./ott/lang_simple.ott  lines 1205 - 1210 
 [
  
   (side-condition ,(not (alpha-equivalent? L (term  (CanonicalAtomic  (AtomicSpine  x  SpineEmpty) ) ) (term  (CanonicalAtomic  (AtomicSpine  y  SpineEmpty) ) )))) 
  (GHsub x gU gu gU gU_^)
  (GradualEnvSub x gU gu Gamma Gamma_^)
  --------------------------------------------------------------------- "GradualEnvSubVarDiff"
  (GradualEnvSub x gU gu (EnvExt y gU Gamma) (EnvExt y gU_^ Gamma_^))]

;; #source file ./ott/lang_simple.ott  lines 1211 - 1214 
 [
  
  (GradualEnvSub x gU gu Gamma Gamma_^)
  ----------------------------------------------------- "GradualEnvSubVarSame"
  (GradualEnvSub x gU gu (EnvExt x gU Gamma) Gamma_^)]

)
(define-judgment-form L 
 
  #:mode (GHsub I I I I O)
  #:contract (GHsub x gU gu_11 gu_22 gu_33)

;; #source file ./ott/lang_simple.ott  lines 1221 - 1223 
 [--------------------------------------------------------------------------------- "GHsubSet"
  (GHsub x gU gu (CanonicalAtomic (AtomicSet i)) (CanonicalAtomic (AtomicSet i)))]

;; #source file ./ott/lang_simple.ott  lines 1225 - 1227 
 [------------------------------------------- "GHsubDyn"
  (GHsub x gU gu CanonicalDyn CanonicalDyn)]

;; #source file ./ott/lang_simple.ott  lines 1228 - 1233 
 [ (side-condition ,(not (alpha-equivalent? L (term  (CanonicalAtomic  (AtomicSpine  x  SpineEmpty) ) ) (term  (CanonicalAtomic  (AtomicSpine  y  SpineEmpty) ) )))) 
  (GHsub x gU gu gU_11 gU_11^)
  (GHsub x gU gu gU_22 gU_22^)
  --------------------------------------------------------------------------- "GHsubPi"
  (GHsub x gU gu (CanonicalPi y gU_11 gU_22) (CanonicalPi y gU_11^ gU_22^))]

;; #source file ./ott/lang_simple.ott  lines 1234 - 1238 
 [ (where   y  ,(gensym)) 
  (GHsub x gU gu (CanonicalPi y gU_11  (substitute  gU_22   x   y ) ) gU_33)
  --------------------------------------------------- "GHsubPiRdxAlpha"
  (GHsub x gU gu (CanonicalPi x gU_11 gU_22) gU_33)]

;; #source file ./ott/lang_simple.ott  lines 1240 - 1244 
 [ (side-condition ,(not (alpha-equivalent? L (term  (CanonicalAtomic  (AtomicSpine  x  SpineEmpty) ) ) (term  (CanonicalAtomic  (AtomicSpine  y  SpineEmpty) ) )))) 
  (GHsub x gU gu gu_22 gu_33)
  ------------------------------------------------------------------- "GHsubLam"
  (GHsub x gU gu  (CanonicalLam y gu_22)   (CanonicalLam y gu_33) )]

;; #source file ./ott/lang_simple.ott  lines 1245 - 1249 
 [ (where   y  ,(gensym)) 
  (GHsub x gU gu  (CanonicalLam y  (substitute  gu_22   x   y ) )  gu_33)
  ------------------------------------------------ "GHsubLamRdxAlpha"
  (GHsub x gU gu  (CanonicalLam x gu_22)  gu_33)]

;; #source file ./ott/lang_simple.ott  lines 1250 - 1253 
 [ (side-condition ,(not (alpha-equivalent? L (term  (CanonicalAtomic  (AtomicSpine  x  SpineEmpty) ) ) (term  (CanonicalAtomic  (AtomicSpine  y  SpineEmpty) ) )))) 
  ------------------------------------------------------------------------------------------------------------------- "GHsubDiffNil"
  (GHsub x gU gu (CanonicalAtomic  (AtomicSpine  y  SpineEmpty) ) (CanonicalAtomic  (AtomicSpine  y  SpineEmpty) ))]

;; #source file ./ott/lang_simple.ott  lines 1254 - 1259 
 [ (side-condition ,(not (alpha-equivalent? L (term  (CanonicalAtomic  (AtomicSpine  x  SpineEmpty) ) ) (term  (CanonicalAtomic  (AtomicSpine  y  SpineEmpty) ) )))) 
  (GHsub x gU gu (CanonicalAtomic (AtomicSpine y ge)) (CanonicalAtomic (AtomicSpine y ge_^)))
  (GHsub x gU gu gu_22 gu_33)
  --------------------------------------------------------------------------------------------------------------------------------- "GHsubDiffCons"
  (GHsub x gU gu (CanonicalAtomic (AtomicSpine y (SpineCons ge gu_22))) (CanonicalAtomic (AtomicSpine y (SpineCons ge_^ gu_33))))]

;; #source file ./ott/lang_simple.ott  lines 1262 - 1265 
 [(GHsubR x gU gu ge gu_22 gU_22)
  ------------------------------------------------------------ "GHsubSpine"
  (GHsub x gU gu (CanonicalAtomic (AtomicSpine x ge)) gu_22)]

)
(define-judgment-form L 
 
  #:mode (GHsubR I I I I O O)
  #:contract (GHsubR x gU gu ge gu_22 gU_22)

;; #source file ./ott/lang_simple.ott  lines 1285 - 1287 
 [----------------------------------- "GHsubRHead"
  (GHsubR x gU gu SpineEmpty gu gU)]

;; #source file ./ott/lang_simple.ott  lines 1290 - 1294 
 [ (GHsubR x gU gu ge CanonicalDyn (CanonicalPi y gU_11 gU_22))   (GHsub y gU_11 gu_22 gU_22 gU_33) 
  ---------------------------------------------------------- "GHsubRDynSpine"
  (GHsubR x gU gu (SpineCons ge gu_22) CanonicalDyn gU_33)]

;; #source file ./ott/lang_simple.ott  lines 1295 - 1300 

;; #source file ./ott/lang_simple.ott  lines 1301 - 1306 
 [(GHsubR x gU gu_11 ge gu_22 CanonicalDyn)
  -------------------------------------------------------------------- "GHsubRDynType"
  (GHsubR x gU gu_11 (SpineCons ge gu_22) CanonicalDyn CanonicalDyn)]

;; #source file ./ott/lang_simple.ott  lines 1309 - 1315 
 [(GHsubR x gU gu ge  (CanonicalLam y_11 gu_22)  (CanonicalPi y_22 gU_11 gU_22))
   (GHsub x gU gu gu_11 gu_33)   (GHsub y_11 gU_11 gu_33 gu_22 gu_44) 
   (GHsub y_22 gU_11 gu_33 gU_22 gU_33)   (GEtaExpandC gu_44 gu_55 gU_33) 
  --------------------------------------------------- "GHsubRLamSpineRdxAlpha"
  (GHsubR x gU gu (SpineCons ge gu_11) gu_55 gU_33)]

)
(define-judgment-form L 
 
  #:mode (CodSub I I O)
  #:contract (CodSub gu gU gU_^)

;; #source file ./ott/lang_simple.ott  lines 1326 - 1329 
 [(GHsub x gU_11 gu gU_22 gU_22^)
  ------------------------------------------------ "CodSubPi"
  (CodSub gu (CanonicalPi x gU_11 gU_22) gU_22^)]

;; #source file ./ott/lang_simple.ott  lines 1330 - 1332 
 [--------------------------------------- "CodSubDyn"
  (CodSub gu CanonicalDyn CanonicalDyn)]

)
(define-judgment-form L 
 
  #:mode (BodySub I I I O)
  #:contract (BodySub gU gu gu_22 gu_33)

;; #source file ./ott/lang_simple.ott  lines 1358 - 1361 
 [(GHsub x gU gu gu_22 gu_22^)
  ------------------------------------------------- "BodySubPi"
  (BodySub gU gu  (CanonicalLam x gu_22)  gu_22^)]

;; #source file ./ott/lang_simple.ott  lines 1362 - 1364 
 [------------------------------------------- "BodySubDyn"
  (BodySub gU gu CanonicalDyn CanonicalDyn)]
)

;;; definitions 

(define-judgment-form
  L
  #:mode (GradualSet I I)
  #:contract (GradualSet Gamma gU)

;; #source file ./ott/lang_simple.ott  lines 1375 - 1378 
 [
  (GCSynth Gamma grr CanonicalDyn)
  ------------------------------------------ "GradualSetDynTy"
  (GradualSet Gamma (CanonicalAtomic grr))]

;; #source file ./ott/lang_simple.ott  lines 1379 - 1382 
 [
  (GCSynth Gamma grr (CanonicalAtomic (AtomicSet i)))
  ------------------------------------------ "GradualSetSet"
  (GradualSet Gamma (CanonicalAtomic grr))]

;; #source file ./ott/lang_simple.ott  lines 1385 - 1390 
 [
  (GradualSet Gamma gU_11)
    
  (GradualSet (EnvExt x gU_11 Gamma) gU_22)
  ------------------------------------------------ "GradualSetPi"
  (GradualSet Gamma (CanonicalPi x gU_11 gU_22))]

;; #source file ./ott/lang_simple.ott  lines 1392 - 1394 
 [
  --------------------------------- "GradualSetDynVal"
  (GradualSet Gamma CanonicalDyn)]

)
(define-judgment-form L 
 
  #:mode (WF I)
  #:contract (WF Gamma)

;; #source file ./ott/lang_simple.ott  lines 1400 - 1402 
 [--------------- "WFEmpty"
  (WF EnvEmpty)]

;; #source file ./ott/lang_simple.ott  lines 1403 - 1407 
 [
   (WF Gamma)   (GradualSet Gamma gU) 
  (GVarFree x Gamma)
  -------------------------- "WFExt"
  (WF (EnvExt x gU Gamma))]

)
(define-judgment-form L 
 
  #:mode (GCSynth I I O)
  #:contract (GCSynth Gamma grr gU)

;; #source file ./ott/lang_simple.ott  lines 1413 - 1416 
 [
   (side-condition ,(> (term  i ) 0)) 
  --------------------------------------------------------------------------- "GCSynthSet"
  (GCSynth Gamma (AtomicSet i) (CanonicalAtomic  (AtomicSet (succ  i ) ) ))]

;; #source file ./ott/lang_simple.ott  lines 1418 - 1422 
 [
    
  (GVarLook x gU Gamma)
  --------------------------------------------------- "GCSynthVar"
  (GCSynth Gamma  (AtomicSpine  x  SpineEmpty)  gU)]

;; #source file ./ott/lang_simple.ott  lines 1426 - 1433 
 [
  (GCSynth Gamma (AtomicSpine x ge) gU)
  (Domain gU gU_22)
  (GCCheck Gamma gu gU_22)
  (CodSub gu gU gU_33)
  --------------------------------------------------------- "GCSynthApp"
  (GCSynth Gamma (AtomicSpine x (SpineCons ge gu)) gU_33)]

)
(define-judgment-form L 
 
  #:mode (GCCheck I I I)
  #:contract (GCCheck Gamma gu gU)

;; #source file ./ott/lang_simple.ott  lines 1440 - 1444 
 [
  (GCSynth Gamma grr gU)
  (Consistent gU gU_^)
  -------------------------------------------- "GCCheckSynth"
  (GCCheck Gamma (CanonicalAtomic grr) gU_^)]

;; #source file ./ott/lang_simple.ott  lines 1445 - 1449 
 [
  (GCSynth Gamma gRR (CanonicalAtomic (AtomicSet i)))
   (side-condition ,(and (< 0 (term  i )) (< (term  i ) (term  j )))) 
  ----------------------------------------------------------------------- "GCCheckLevel"
  (GCCheck Gamma (CanonicalAtomic gRR) (CanonicalAtomic (AtomicSet j)))]

;; #source file ./ott/lang_simple.ott  lines 1451 - 1455 

;; #source file ./ott/lang_simple.ott  lines 1457 - 1462 
 [
   (where   z  ,(gensym)) 
    
  (GCCheck (EnvExt z gU_11 Gamma)  (substitute  gu   x   z )   (substitute  gU_22   y   z ) )
  ------------------------------------------------------------------- "GCCheckLamPiRdxAlpha"
  (GCCheck Gamma  (CanonicalLam x gu)  (CanonicalPi y gU_11 gU_22))]

;; #source file ./ott/lang_simple.ott  lines 1463 - 1467 
 [
    
  (GCCheck (EnvExt x CanonicalDyn Gamma) gu CanonicalDyn)
  ---------------------------------------------------- "GCCheckLamDyn"
  (GCCheck Gamma  (CanonicalLam x gu)  CanonicalDyn)]

;; #source file ./ott/lang_simple.ott  lines 1468 - 1474 
 [
  (ConsistentSet gU_33)
  (GCCheck Gamma gU_11 gU_33)
    
  (GCCheck (EnvExt x gU_11 Gamma) gU_22 gU_33)
  --------------------------------------------------- "GCCheckPi"
  (GCCheck Gamma (CanonicalPi x gU_11 gU_22) gU_33)]

;; #source file ./ott/lang_simple.ott  lines 1476 - 1479 
 [
  (GradualSet Gamma gU)
  --------------------------------- "GCCheckDyn"
  (GCCheck Gamma CanonicalDyn gU)]

)
(define-judgment-form L 
 
  #:mode (ConsistentSet I)
  #:contract (ConsistentSet gU)

;; #source file ./ott/lang_simple.ott  lines 1487 - 1489 
 [------------------------------------------------- "ConsistentSetSet"
  (ConsistentSet (CanonicalAtomic (AtomicSet i)))]

;; #source file ./ott/lang_simple.ott  lines 1490 - 1492 
 [------------------------------ "ConsistentSetDyn"
  (ConsistentSet CanonicalDyn)]

)
(define-judgment-form L 
 
  #:mode (Consistent I I)
  #:contract (Consistent gU gU_^)

;; #source file ./ott/lang_simple.ott  lines 1502 - 1504 
 [-------------------- "ConsistentEq"
  (Consistent gu gu)]

;; #source file ./ott/lang_simple.ott  lines 1505 - 1509 

;; #source file ./ott/lang_simple.ott  lines 1511 - 1516 
 [ (where   z  ,(gensym)) 
  (Consistent gU_11 gU_11^)
  (Consistent  (substitute  gU_22   x   z )   (substitute  gU_22^   y   z ) )
  ------------------------------------------------------------------------ "ConsistentPiRdxAlpha"
  (Consistent (CanonicalPi x gU_11 gU_22) (CanonicalPi y gU_11^ gU_22^))]

;; #source file ./ott/lang_simple.ott  lines 1517 - 1520 

;; #source file ./ott/lang_simple.ott  lines 1522 - 1526 
 [ (where   z  ,(gensym)) 
  (Consistent  (substitute  gu   x   z )   (substitute  gu_^   y   z ) )
  ------------------------------------------------------------ "ConsistentLamRdxAlpha"
  (Consistent  (CanonicalLam x gu)   (CanonicalLam y gu_^) )]

;; #source file ./ott/lang_simple.ott  lines 1527 - 1531 
 [(Consistent (CanonicalAtomic (AtomicSpine x ge)) (CanonicalAtomic (AtomicSpine x ge_^)))
  (Consistent gu gu_^)
  -------------------------------------------------------------------------------------------------------------------------- "ConsistentApp"
  (Consistent (CanonicalAtomic (AtomicSpine x (SpineCons ge gu))) (CanonicalAtomic (AtomicSpine x (SpineCons ge_^ gu_^))))]

;; #source file ./ott/lang_simple.ott  lines 1532 - 1534 
 [------------------------------ "ConsistentDynL"
  (Consistent CanonicalDyn gu)]

;; #source file ./ott/lang_simple.ott  lines 1535 - 1537 
 [------------------------------ "ConsistentDynR"
  (Consistent gu CanonicalDyn)]
)

;;; definitions 

(define-judgment-form
  L
  #:mode (Meet I I O)
  #:contract (Meet gU_11 gU_22 gU_33)

;; #source file ./ott/lang_simple.ott  lines 1549 - 1553 

;; #source file ./ott/lang_simple.ott  lines 1555 - 1560 
 [ (where   z  ,(gensym)) 
  (Meet gU_11 gU_11^ gU_11^^)
  (Meet  (substitute  gU_22   x   z )   (substitute  gU_22^   y   z )  gU_22^^)
  -------------------------------------------------------------------------------------------------- "MeetPiRdxAlpha"
  (Meet (CanonicalPi x gU_11 gU_22) (CanonicalPi y gU_11^ gU_22^) (CanonicalPi z gU_11^^ gU_22^^))]

;; #source file ./ott/lang_simple.ott  lines 1561 - 1564 

;; #source file ./ott/lang_simple.ott  lines 1566 - 1570 
 [ (where   z  ,(gensym)) 
  (Meet  (substitute  gu   x   z )   (substitute  gu_^   y   z )  gu_^^)
  ------------------------------------------------------------------------- "MeetLamRdxAlpha"
  (Meet (CanonicalLam x gu) (CanonicalLam y gu_^) (CanonicalLam z gu_^^))]

;; #source file ./ott/lang_simple.ott  lines 1571 - 1575 
 [(Meet gu gu_^ gu_^^)
  (Meet (CanonicalAtomic (AtomicSpine x ge)) (CanonicalAtomic (AtomicSpine x ge_^)) (CanonicalAtomic (AtomicSpine x ge_^^)))
  ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------ "MeetApp"
  (Meet (CanonicalAtomic (AtomicSpine x (SpineCons ge gu))) (CanonicalAtomic (AtomicSpine x (SpineCons ge_^ gu_^))) (CanonicalAtomic (AtomicSpine x (SpineCons ge_^^ gu_^^))))]

;; #source file ./ott/lang_simple.ott  lines 1576 - 1578 
 [--------------------------- "MeetDynL"
  (Meet CanonicalDyn gU gU)]

;; #source file ./ott/lang_simple.ott  lines 1579 - 1582 
 [ (side-condition ,(not (alpha-equivalent? L (term  gU ) (term  CanonicalDyn )))) 
  --------------------------- "MeetDynR"
  (Meet gU CanonicalDyn gU)]

;; #source file ./ott/lang_simple.ott  lines 1583 - 1586 
 [ (side-condition ,(not (alpha-equivalent? L (term  gu ) (term  CanonicalDyn )))) 
  ----------------- "MeetRefl"
  (Meet gu gu gu)]

)
(define-judgment-form L 
 
  #:mode (MorePrecise I I)
  #:contract (MorePrecise gU gU_^)

;; #source file ./ott/lang_simple.ott  lines 1594 - 1598 

;; #source file ./ott/lang_simple.ott  lines 1600 - 1605 
 [ (where   z  ,(gensym)) 
  (MorePrecise gU_11 gU_11^)
  (MorePrecise  (substitute  gU_22   x   z )   (substitute  gU_22^   y   z ) )
  ------------------------------------------------------------------------- "MorePrecisePiRdxAlpha"
  (MorePrecise (CanonicalPi x gU_11 gU_22) (CanonicalPi y gU_11^ gU_22^))]

;; #source file ./ott/lang_simple.ott  lines 1606 - 1609 

;; #source file ./ott/lang_simple.ott  lines 1611 - 1615 
 [ (where   z  ,(gensym)) 
  (MorePrecise  (substitute  gu   x   z )   (substitute  gu_^   y   z ) )
  --------------------------------------------------------- "MorePreciseLamRdxAlpha"
  (MorePrecise (CanonicalLam x gu) (CanonicalLam y gu_^))]

;; #source file ./ott/lang_simple.ott  lines 1616 - 1620 
 [(MorePrecise gu gu_^)
  (MorePrecise (CanonicalAtomic (AtomicSpine x ge)) (CanonicalAtomic (AtomicSpine x ge_^)))
  --------------------------------------------------------------------------------------------------------------------------- "MorePreciseApp"
  (MorePrecise (CanonicalAtomic (AtomicSpine x (SpineCons ge gu))) (CanonicalAtomic (AtomicSpine x (SpineCons ge_^ gu_^))))]

;; #source file ./ott/lang_simple.ott  lines 1622 - 1624 
 [------------------------------- "MorePreciseDyn"
  (MorePrecise gU CanonicalDyn)]

;; #source file ./ott/lang_simple.ott  lines 1625 - 1628 
 [ (side-condition ,(not (alpha-equivalent? L (term  gU ) (term  CanonicalDyn )))) 
  --------------------- "MorePreciseRefl"
  (MorePrecise gU gU)]

)
(define-judgment-form L 
 
  #:mode (TermPrecise I I)
  #:contract (TermPrecise gt gt_^)

;; #source file ./ott/lang_simple.ott  lines 1636 - 1640 

;; #source file ./ott/lang_simple.ott  lines 1644 - 1647 

;; #source file ./ott/lang_simple.ott  lines 1650 - 1654 
 [
  
  (TermPrecise gt_11 gt_11^)
  (TermPrecise gt_22 gt_22^)
  ------------------------------------------------------------- "TermPreciseApp"
  (TermPrecise (TermApp gt_11 gt_22) (TermApp gt_11^ gt_22^))]

;; #source file ./ott/lang_simple.ott  lines 1655 - 1659 
 [
  
  (TermPrecise gt_11 gt_22)
  (TermPrecise gT_11 gT_22)
  ----------------------------------------------------------- "TermPreciseAscr"
  (TermPrecise (TermAnn gt_11 gT_11) (TermAnn gt_22 gT_22))]

;; #source file ./ott/lang_simple.ott  lines 1660 - 1663 
 [
  -------------------------- "TermPreciseDyn"
  (TermPrecise gt TermDyn)]

;; #source file ./ott/lang_simple.ott  lines 1664 - 1666 
 [--------------------- "TermPreciseRefl"
  (TermPrecise gT gT)]

)
(define-judgment-form L 
 
  #:mode (EvPrecise I I)
  #:contract (EvPrecise et et_^)

;; #source file ./ott/lang_simple.ott  lines 1673 - 1677 

;; #source file ./ott/lang_simple.ott  lines 1680 - 1683 

;; #source file ./ott/lang_simple.ott  lines 1685 - 1689 
 [
  
  (EvPrecise et_11 et_11^)
  (EvPrecise et_22 et_22^)
  ----------------------------------------------------------- "EvPreciseApp"
  (EvPrecise (TermApp et_11 et_22) (TermApp et_11^ et_22^))]

;; #source file ./ott/lang_simple.ott  lines 1690 - 1694 
 [
  
  (EvPrecise et_11 et_22)
  (MorePrecise  (type-in-ev  ep_11 )   (type-in-ev  ep_22 ) )
  ------------------------------------------------------- "EvPreciseAscr"
  (EvPrecise (TermEp ep_11 et_11) (TermEp ep_22 et_22))]

;; #source file ./ott/lang_simple.ott  lines 1695 - 1697 
 [------------------------ "EvPreciseDyn"
  (EvPrecise eT TermDyn)]

;; #source file ./ott/lang_simple.ott  lines 1698 - 1700 
 [-------------------------- "EvPreciseErr"
  (EvPrecise TermError eT)]

;; #source file ./ott/lang_simple.ott  lines 1701 - 1703 
 [------------------- "EvPreciseRefl"
  (EvPrecise eT eT)]

)
(define-judgment-form L 
 
  #:mode (EvConsistent I I I)
  #:contract (EvConsistent ep gU gU_^)

;; #source file ./ott/lang_simple.ott  lines 1710 - 1714 
 [
  (Meet gU_11 gU_22 gU_33)
  (MorePrecise gU gU_33)
  -------------------------------------------------- "EvConsistentDef"
  (EvConsistent (EvidenceEv Gamma gU) gU_11 gU_22)]
)
;; #source file ./ott/lang_simple.ott  lines 1715 - 1715 
#| 

;;; definitions 

(define-judgment-form
  L
  #:mode (EtaPrecise I I)
  #:contract (EtaPrecise gu gu_^)

)
(define-judgment-form L 
 
  #:mode (GammaPrecise I I)
  #:contract (GammaPrecise Gamma Gamma_^)

)
(define-judgment-form L 
 
  #:mode (EtaGammaPrecise I I)
  #:contract (EtaGammaPrecise Gamma Gamma_^)

)
;; #source file ./ott/lang_simple.ott  lines 1732 - 1732 
|# 

;;; definitions 

(define-judgment-form
  L
  #:mode (GSynth I I O)
  #:contract (GSynth Gamma gtSynth gU)

;; #source file ./ott/lang_simple.ott  lines 1750 - 1754 
 [
  
  (GradualSetNorm Gamma gU gT)
  (GCheck Gamma gt gU)
  ------------------------------------- "GSynthAnn"
  (GSynth Gamma  (TermAnn gt gT)  gU)]

;; #source file ./ott/lang_simple.ott  lines 1755 - 1758 
 [
   (side-condition ,(> (term  i ) 0)) 
  ------------------------------------------------------------------------ "GSynthSet"
  (GSynth Gamma (TermSet i) (CanonicalAtomic  (AtomicSet (succ  i ) ) ))]

;; #source file ./ott/lang_simple.ott  lines 1760 - 1764 
 [
  (GVarLook x gU Gamma)
    
  ------------------------------- "GSynthVar"
  (GSynth Gamma x gU)]

;; #source file ./ott/lang_simple.ott  lines 1769 - 1774 
 [
  
   (GSynth Gamma gtSynth_11 gU)      
    (Domain gU gU_^)   (GNCheck Gamma gu gt_22 gU_^)  
  (CodSub gu gU gU_22)
  ------------------------------------------------- "GSynthApp"
  (GSynth Gamma (TermApp gtSynth_11 gt_22) gU_22)]

;; #source file ./ott/lang_simple.ott  lines 1775 - 1778 
 [
  ------------------------------------- "GSynthDyn"
  (GSynth Gamma TermDyn CanonicalDyn)]

)
(define-judgment-form L 
 
  #:mode (GCheck I I I)
  #:contract (GCheck Gamma gt gU)

;; #source file ./ott/lang_simple.ott  lines 1793 - 1798 
 [
  
  (GSynth Gamma gtSynth gU_^)
  (Consistent gU_^ gU)
  --------------------------- "GCheckSynth"
  (GCheck Gamma gtSynth gU)]

;; #source file ./ott/lang_simple.ott  lines 1799 - 1804 
 [
  (GSynth Gamma gTSynth (CanonicalAtomic (AtomicSet i)))
   (side-condition ,(and (< 0 (term  i )) (< (term  i ) (term  j )))) 
  -------------------------------------------------------- "GCheckLevel"
  (GCheck Gamma gTSynth (CanonicalAtomic (AtomicSet j)))]

;; #source file ./ott/lang_simple.ott  lines 1813 - 1817 
 [
  
   (GNCheck Gamma gU_^ gT_11 gU)   (ConsistentSet gU) 
        (GCheck (EnvExt x gU_^ Gamma) gT_22 gU) 
  ------------------------------------------ "GCheckPi"
  (GCheck Gamma (TermPi x gT_11 gT_22) gU)]

;; #source file ./ott/lang_simple.ott  lines 1819 - 1823 

;; #source file ./ott/lang_simple.ott  lines 1825 - 1830 
 [
  
   (where   z  ,(gensym)) 
    
  (GCheck (EnvExt z gU_11 Gamma)  (substitute  gt   x   z )   (substitute  gU_22   y   z ) )
  ------------------------------------------------------------- "GCheckLamPiRdxAlpha"
  (GCheck Gamma  (TermLam x gt)  (CanonicalPi y gU_11 gU_22))]

;; #source file ./ott/lang_simple.ott  lines 1832 - 1836 
 [
  
    
  (GCheck (EnvExt x CanonicalDyn Gamma) gt CanonicalDyn)
  ---------------------------------------------- "GCheckLamDyn"
  (GCheck Gamma  (TermLam x gt)  CanonicalDyn)]

)
(define-judgment-form L 
 
  #:mode (GradualSetNorm I O I)
  #:contract (GradualSetNorm Gamma gU TT)

;; #source file ./ott/lang_simple.ott  lines 1854 - 1857 
 [
  
  (GNSynth Gamma TTSynth gU (CanonicalAtomic (AtomicSet i)))
  ----------------------------------- "GradualSetNormSynth"
  (GradualSetNorm Gamma gU TTSynth)]

;; #source file ./ott/lang_simple.ott  lines 1859 - 1863 
 [
  (GradualSetNorm Gamma gU_11 TT_1_1)
  (GradualSetNorm (EnvExt x gU_11 Gamma) gU_22 TT_2_2)
  ----------------------------------------------------------------------------- "GradualSetNormPi"
  (GradualSetNorm Gamma (CanonicalPi x gU_11 gU_22) (TermPi x TT_1_1 TT_2_2))]

;; #source file ./ott/lang_simple.ott  lines 1865 - 1867 
 [
  --------------------------------------------- "GradualSetNormDyn"
  (GradualSetNorm Gamma CanonicalDyn TermDyn)]

)
(define-judgment-form L 
 
  #:mode (GEtaLong I I)
  #:contract (GEtaLong gu gU)

;; #source file ./ott/lang_simple.ott  lines 1873 - 1875 
 [-------------------------------------------------------- "GEtaLongAtomic"
  (GEtaLong (CanonicalAtomic grr) (CanonicalAtomic gRR))]

;; #source file ./ott/lang_simple.ott  lines 1876 - 1878 
 [----------------------------------------------- "GEtaLongAtomicDyn"
  (GEtaLong (CanonicalAtomic grr) CanonicalDyn)]

;; #source file ./ott/lang_simple.ott  lines 1880 - 1883 

;; #source file ./ott/lang_simple.ott  lines 1884 - 1888 
 [ (where   z  ,(gensym)) 
  (GEtaLong  (substitute  gu   x   z )   (substitute  gU   y   z ) )
  ---------------------------------------------------------- "GEtaLongLamRdxAlpha"
  (GEtaLong  (CanonicalLam x gu)  (CanonicalPi y gU_^ gU))]

;; #source file ./ott/lang_simple.ott  lines 1889 - 1891 
 [---------------------------- "GEtaLongDyn"
  (GEtaLong CanonicalDyn gU)]

;; #source file ./ott/lang_simple.ott  lines 1892 - 1894 
 [------------------------------------------ "GEtaLongPi"
  (GEtaLong (CanonicalPi x gU gU_^) gU_^^)]

)
(define-judgment-form L 
 
  #:mode (GEtaExpand I O I)
  #:contract (GEtaExpand grr gu gU)

;; #source file ./ott/lang_simple.ott  lines 1900 - 1902 
 [-------------------------------------------------------------- "GEtaExpandAtomic"
  (GEtaExpand grr (CanonicalAtomic grr) (CanonicalAtomic gRR))]

;; #source file ./ott/lang_simple.ott  lines 1903 - 1905 
 [----------------------------------------------------- "GEtaExpandDyn"
  (GEtaExpand grr (CanonicalAtomic grr) CanonicalDyn)]

;; #source file ./ott/lang_simple.ott  lines 1907 - 1911 
 [(GEtaExpand  (AtomicSpine  y  SpineEmpty)  gu gU_11)
  (GEtaExpand (AtomicSpine x (SpineCons ge gu)) gu_22 gU_22)
  -------------------------------------------------------------------------------------- "GEtaExpandPi"
  (GEtaExpand (AtomicSpine x ge)  (CanonicalLam y gu_22)  (CanonicalPi y gU_11 gU_22))]

)
(define-judgment-form L 
 
  #:mode (GEtaExpandC I O I)
  #:contract (GEtaExpandC gu gu_^ gU)

;; #source file ./ott/lang_simple.ott  lines 1918 - 1921 
 [(GEtaExpand grr gu gU)
  ------------------------------------------- "GEtaExpandCAtomic"
  (GEtaExpandC (CanonicalAtomic grr) gu gU)]

;; #source file ./ott/lang_simple.ott  lines 1922 - 1925 

;; #source file ./ott/lang_simple.ott  lines 1926 - 1930 
 [ (where   z  ,(gensym)) 
  (GEtaExpandC  (substitute  gu   x   z )  gu_^  (substitute  gU_22   x   z ) )
  ----------------------------------------------------------------------------------------- "GEtaExpandCLamRdxAlpha"
  (GEtaExpandC  (CanonicalLam x gu)   (CanonicalLam z gu_^)  (CanonicalPi y gU_11 gU_22))]

;; #source file ./ott/lang_simple.ott  lines 1931 - 1935 
 [(GEtaExpandC gU_11 gU_11^ gU_^^)
  (GEtaExpandC gU_22 gU_22^ gU_^^)
  ------------------------------------------------------------------------------- "GEtaExpandCPi"
  (GEtaExpandC (CanonicalPi x gU_11 gU_22) (CanonicalPi x gU_11^ gU_22^) gU_^^)]

;; #source file ./ott/lang_simple.ott  lines 1937 - 1939 
 [-------------------------------------------- "GEtaExpandCDyn"
  (GEtaExpandC CanonicalDyn CanonicalDyn gU)]

;; #source file ./ott/lang_simple.ott  lines 1940 - 1942 
 [---------------------------------- "GEtaExpandCDynType"
  (GEtaExpandC gu gu CanonicalDyn)]

)
(define-judgment-form L 
 
  #:mode (GNSynth I I O O)
  #:contract (GNSynth Gamma tt gu gU)

;; #source file ./ott/lang_simple.ott  lines 1963 - 1967 
 [
  (GradualSetNorm Gamma gU TT)
  (GNCheck Gamma gu tt gU)
  ----------------------------------------- "GNSynthAnn"
  (GNSynth Gamma  (TermAnn tt TT)  gu gU)]

;; #source file ./ott/lang_simple.ott  lines 1968 - 1971 
 [
   (side-condition ,(> (term  i ) 0)) 
  --------------------------------------------------------------------------------------------------------- "GNSynthSet"
  (GNSynth Gamma (TermSet i) (CanonicalAtomic (AtomicSet i)) (CanonicalAtomic  (AtomicSet (succ  i ) ) ))]

;; #source file ./ott/lang_simple.ott  lines 1973 - 1979 
 [
   (side-condition ,(not (hash-has-key? currently-defined-vars (term  x )) )) 
    
  (GVarLook x gU Gamma)
  (GEtaExpand  (AtomicSpine  x  SpineEmpty)  gu gU)
  ----------------------------------- "GNSynthVar"
  (GNSynth Gamma x gu gU)]

;; #source file ./ott/lang_simple.ott  lines 1980 - 1983 
 [
  
   (where (ENTTriple  et   gu   gU ) ,(and (hash-has-key? currently-defined-vars (term  x ) ) (hash-ref currently-defined-vars (term  x )) )) 
  ----------------------------------- "GNSynthVarLook"
  (GNSynth Gamma x gu gU)]

;; #source file ./ott/lang_simple.ott  lines 1988 - 1995 
 [
      (where   x  ,(gensym))    (GNSynth Gamma tt_11 gu_11 gU)    (GEtaExpandC gu_11 gu_11^ (CanonicalPi x CanonicalDyn CanonicalDyn))  
    
   (Domain gU gU_11)   (GNCheck Gamma gu_22 tt_22 gU_11) 
  (BodySub gU_11 gu_22 gu_11^ gu_33)
   (CodSub gu_22 gU gU_22)   (GEtaExpandC gu_33 gu_33^ gU_22) 
  ---------------------------------------------------- "GNSynthApp"
  (GNSynth Gamma (TermApp tt_11 tt_22) gu_33^ gU_22)]

;; #source file ./ott/lang_simple.ott  lines 1997 - 2000 
 [
  --------------------------------------------------- "GNSynthDyn"
  (GNSynth Gamma TermDyn CanonicalDyn CanonicalDyn)]

)
(define-judgment-form L 
 
  #:mode (GNSynthCheck I O I I I I)
  #:contract (GNSynthCheck Gamma gu ttSynth gu_^ gU_^ gU)

;; #source file ./ott/lang_simple.ott  lines 2007 - 2010 
 [
   (side-condition ,(and (< 0 (term  i )) (< (term  i ) (term  j )))) 
  ---------------------------------------------------------------------------------------------------- "GNSynthCheckLevel"
  (GNSynthCheck Gamma gU TTSynth gU (CanonicalAtomic (AtomicSet i)) (CanonicalAtomic (AtomicSet j)))]

;; #source file ./ott/lang_simple.ott  lines 2011 - 2015 
 [
  
  (Meet gU gU_^ gU_^^)
   (where  gu  ,(if (alpha-equivalent? (term  gU_^ ) (term  gU_^^ )) (term  gu ) (term  CanonicalDyn ))) 
  -------------------------------------------- "GNSynthCheckConsistent"
  (GNSynthCheck Gamma gu ttSynth gu gU_^ gU)]

)
(define-judgment-form L 
 
  #:mode (GNCheck I O I I)
  #:contract (GNCheck Gamma gu tt gU)

;; #source file ./ott/lang_simple.ott  lines 2023 - 2027 
 [
  
  (GNSynth Gamma ttSynth gu_^ gU_^)
  (GNSynthCheck Gamma gu ttSynth gu_^ gU_^ gU)
  ------------------------------- "GNCheckSynthRdx"
  (GNCheck Gamma gu ttSynth gU)]

;; #source file ./ott/lang_simple.ott  lines 2028 - 2034 

;; #source file ./ott/lang_simple.ott  lines 2036 - 2042 

;; #source file ./ott/lang_simple.ott  lines 2043 - 2048 

;; #source file ./ott/lang_simple.ott  lines 2050 - 2058 
 [
  (ConsistentSet gU_33)
  (GNCheck Gamma gU_11 TT_11 gU_33)
    
  (GNCheck (EnvExt x gU_11 Gamma) gU_22 TT_22 gU_33)
  -------------------------------------------------------------------------- "GNCheckPi"
  (GNCheck Gamma (CanonicalPi x gU_11 gU_22) (TermPi x TT_11 TT_22) gU_33)]

;; #source file ./ott/lang_simple.ott  lines 2059 - 2063 

;; #source file ./ott/lang_simple.ott  lines 2064 - 2069 
 [
   (where   z  ,(gensym)) 
    
  (GNCheck (EnvExt z gU_11 Gamma) gu  (substitute  tt   x   z )   (substitute  gU_22   y   z ) )
  ------------------------------------------------------------------------------------ "GNCheckLamPiRdxAlpha"
  (GNCheck Gamma  (CanonicalLam z gu)   (TermLam x tt)  (CanonicalPi y gU_11 gU_22))]

;; #source file ./ott/lang_simple.ott  lines 2070 - 2074 
 [
    
  (GNCheck (EnvExt x CanonicalDyn Gamma) gu tt CanonicalDyn)
  --------------------------------------------------------------------- "GNCheckLamDyn"
  (GNCheck Gamma  (CanonicalLam x gu)   (TermLam x tt)  CanonicalDyn)]

;; #source file ./ott/lang_simple.ott  lines 2078 - 2083 
 [
  (GNSynth Gamma ett gu gU_^)
  (Consistent gU gU_^)
  (MorePrecise gU_^ gU)
  --------------------------------------- "GNCheckEvUp"
  (GNCheck Gamma gu (TermEp ep ett) gU)]

;; #source file ./ott/lang_simple.ott  lines 2084 - 2089 
 [
  (GNSynth Gamma ett gu gU_^)
   (side-condition ,(not (judgment-holds (MorePrecise  gU_^   gU )))) 
  ------------------------------------------------- "GNCheckEvDown"
  (GNCheck Gamma CanonicalDyn (TermEp ep ett) gU)]

)
(define-judgment-form L 
 
  #:mode (GElabSynth I I O O)
  #:contract (GElabSynth Gamma gtSynth et gU)

;; #source file ./ott/lang_simple.ott  lines 2102 - 2106 
 [
  
  (GradualSetNorm Gamma gU gT)
  (GElabCheck Gamma et gt gU)
  -------------------------------------------- "GElabSynthAnn"
  (GElabSynth Gamma  (TermAnn gt gT)  et gU)]

;; #source file ./ott/lang_simple.ott  lines 2107 - 2110 
 [
   (side-condition ,(> (term  i ) 0)) 
  ---------------------------------------------------------------------------------------- "GElabSynthSet"
  (GElabSynth Gamma (TermSet i) (TermSet i) (CanonicalAtomic  (AtomicSet (succ  i ) ) ))]

;; #source file ./ott/lang_simple.ott  lines 2112 - 2117 
 [
   (side-condition ,(not (hash-has-key? currently-defined-vars (term  x )) )) 
    
  (GVarLook x gU Gamma)
  ----------------------------------------------- "GElabSynthVar"
  (GElabSynth Gamma x x gU)]

;; #source file ./ott/lang_simple.ott  lines 2118 - 2121 
 [
  
   (where (ENTTriple  et   gu   gU ) ,(and (hash-has-key? currently-defined-vars (term  x ) ) (hash-ref currently-defined-vars (term  x )) )) 
  -------------------------------------- "GElabSynthVarLook"
  (GElabSynth Gamma x et gU)]

;; #source file ./ott/lang_simple.ott  lines 2125 - 2131 
 [
  
  (GElabSynth Gamma gtSynth_11 et_11 gU)
  (Domain gU gU_11)
  (GradualNECheck Gamma gu et_22 gt_22 gU_11)
  (CodSub gu gU gU_22)
  --------------------------------------------------------------------------- "GElabSynthApp"
  (GElabSynth Gamma (TermApp gtSynth_11 gt_22) (TermApp et_11 et_22) gU_22)]

;; #source file ./ott/lang_simple.ott  lines 2132 - 2135 
 [
  ------------------------------------------------------------------------------------------ "GElabSynthDyn"
  (GElabSynth Gamma TermDyn (TermEp (EvidenceEv Gamma CanonicalDyn) TermDyn) CanonicalDyn)]

)
(define-judgment-form L 
 
  #:mode (GElabSynthCheck I O I I I I)
  #:contract (GElabSynthCheck Gamma et_^ gtSynth et gU_^ gU)

;; #source file ./ott/lang_simple.ott  lines 2143 - 2146 
 [
   (side-condition ,(and (< 0 (term  i )) (< (term  i ) (term  j )))) 
  ------------------------------------------------------------------------------------------------------- "GElabSynthCheckLevel"
  (GElabSynthCheck Gamma eT gTSynth eT (CanonicalAtomic (AtomicSet i)) (CanonicalAtomic (AtomicSet j)))]

;; #source file ./ott/lang_simple.ott  lines 2150 - 2154 
 [
  
  (Meet gU_^^ gU gU_^)
  --------------------------------------------------------------------------------- "GElabSynthCheckConsistent"
  (GElabSynthCheck Gamma (TermEp (EvidenceEv Gamma gU_^) et) gtSynth et gU gU_^^)]

)
(define-judgment-form L 
 
  #:mode (GElabCheck I O I I)
  #:contract (GElabCheck Gamma et gt gU)

;; #source file ./ott/lang_simple.ott  lines 2168 - 2173 
 [
  
  (GElabSynth Gamma gtSynth et_^ gU_^)
  (GElabSynthCheck Gamma et gtSynth et_^ gU_^ gU)
  ---------------------------------- "GElabCheckSynthRdx"
  (GElabCheck Gamma et gtSynth gU)]

;; #source file ./ott/lang_simple.ott  lines 2174 - 2180 

;; #source file ./ott/lang_simple.ott  lines 2181 - 2186 

;; #source file ./ott/lang_simple.ott  lines 2196 - 2204 
 [
  (ConsistentSet gU)
  (GradualNECheck Gamma gU_11 eT_11 gT_11 gU)
    
  (GElabCheck (EnvExt x gU_11 Gamma) eT_22 gT_22 gU)
  --------------------------------------------------------------------- "GElabCheckPi"
  (GElabCheck Gamma (TermPi x eT_11 eT_22) (TermPi x gT_11 gT_22) gU)]

;; #source file ./ott/lang_simple.ott  lines 2205 - 2209 

;; #source file ./ott/lang_simple.ott  lines 2210 - 2215 
 [
  
   (where   z  ,(gensym)) 
    
  (GElabCheck (EnvExt z gU_11 Gamma) et  (substitute  gt   x   z )   (substitute  gU_22   y   z ) )
  ---------------------------------------------------------------------------------- "GElabCheckLamPiRdxAlpha"
  (GElabCheck Gamma  (TermLam z et)   (TermLam x gt)  (CanonicalPi y gU_11 gU_22))]

;; #source file ./ott/lang_simple.ott  lines 2216 - 2220 
 [
  
    
  (GElabCheck (EnvExt x CanonicalDyn Gamma) et gt CanonicalDyn)
  ------------------------------------------------------------------- "GElabCheckLamDyn"
  (GElabCheck Gamma  (TermLam x et)   (TermLam x gt)  CanonicalDyn)]

)
(define-judgment-form L 
 
  #:mode (GradualNESynth I I O O O)
  #:contract (GradualNESynth Gamma gtSynth et gu gU)

;; #source file ./ott/lang_simple.ott  lines 2236 - 2240 
 [
  
  (GradualSetNorm Gamma gU gT)
  (GradualNECheck Gamma gu et gt gU)
  --------------------------------------------------- "GradualNESynthAnn"
  (GradualNESynth Gamma  (TermAnn gt gT)  et gu gU)]

;; #source file ./ott/lang_simple.ott  lines 2241 - 2244 
 [
   (side-condition ,(> (term  i ) 0)) 
  ---------------------------------------------------------------------------------------------------------------------------- "GradualNESynthSet"
  (GradualNESynth Gamma (TermSet i) (TermSet i) (CanonicalAtomic (AtomicSet i)) (CanonicalAtomic  (AtomicSet (succ  i ) ) ))]

;; #source file ./ott/lang_simple.ott  lines 2246 - 2252 
 [
   (side-condition ,(not (hash-has-key? currently-defined-vars (term  x )) )) 
    
  (GVarLook x gU Gamma)
  (GEtaExpand  (AtomicSpine  x  SpineEmpty)  gu gU)
  ------------------------------------------------------ "GradualNESynthVar"
  (GradualNESynth Gamma x x gu gU)]

;; #source file ./ott/lang_simple.ott  lines 2253 - 2256 
 [
  
   (where (ENTTriple  et   gu   gU ) ,(and (hash-has-key? currently-defined-vars (term  x ) ) (hash-ref currently-defined-vars (term  x )) )) 
  --------------------------------------------- "GradualNESynthVarLook"
  (GradualNESynth Gamma x et gu gU)]

;; #source file ./ott/lang_simple.ott  lines 2260 - 2270 
 [
  
  (GradualNESynth Gamma gtSynth_11 et_11 gu gU)
     (where   x  ,(gensym))    (GEtaExpandC gu gu_^ (CanonicalPi x CanonicalDyn CanonicalDyn))  
    
  (Domain gU gU_11)
  (GradualNECheck Gamma gu_22 et_22 gt_22 gU_11)
  (BodySub gU_11 gu_22 gu_^ gu_^^)
  (CodSub gu_22 gU gU_22)
  (GEtaExpandC gu_^^ gu_^^^ gU_22)
  -------------------------------------------------------------------------------------- "GradualNESynthApp"
  (GradualNESynth Gamma (TermApp gtSynth_11 gt_22) (TermApp et_11 et_22) gu_^^^ gU_22)]

;; #source file ./ott/lang_simple.ott  lines 2273 - 2277 
 [
   (side-condition ,(error 'typechecking "Cannot synthesize type for ~a, try adding an annotation?" (pt (term  (TermVar gs) )))) 
  ----------------------------------------------------------------------------------------------------------------------------------------- "GradualNESynthSynthRdxError"
  (GradualNESynth Gamma (TermVar gs) (TermSet  0 ) (CanonicalAtomic (AtomicSet  0 )) (CanonicalAtomic  (AtomicSpine  Set0  SpineEmpty) ))]

)
(define-judgment-form L 
 
  #:mode (GradualNESynthCheck I O O I I I I I)
  #:contract (GradualNESynthCheck Gamma gu et_11 gtSynth gu_^ et gU_^ gU)

;; #source file ./ott/lang_simple.ott  lines 2285 - 2288 
 [
   (side-condition ,(and (< 0 (term  i )) (< (term  i ) (term  j )))) 
  ----------------------------------------------------------------------------------------------------------------- "GradualNESynthCheckLevel"
  (GradualNESynthCheck Gamma gU eT gTSynth gU eT (CanonicalAtomic (AtomicSet i)) (CanonicalAtomic (AtomicSet j)))]

;; #source file ./ott/lang_simple.ott  lines 2294 - 2298 
 [
  
  (Meet gU gU_^ gU_^^)
   (where  gu_^^  ,(if (alpha-equivalent? (term  gU_^ ) (term  gU_^^ )) (term  gu_^ ) (term  CanonicalDyn ))) 
  ---------------------------------------------------------------------------------------------------- "GradualNESynthCheckConsistent"
  (GradualNESynthCheck Gamma gu_^^ (TermEp (EvidenceEv Gamma gU_^^) et_^) gtSynth gu_^ et_^ gU_^ gU)]

)
(define-judgment-form L 
 
  #:mode (GradualNECheck I O O I I)
  #:contract (GradualNECheck Gamma gu et gt gU)

;; #source file ./ott/lang_simple.ott  lines 2315 - 2319 
 [
  
  (GradualNESynth Gamma gtSynth et_^ gu_^ gU_^)
  (GradualNESynthCheck Gamma gu_^^ et_^^ gtSynth gu_^ et_^ gU_^ gU)
  ----------------------------------------------- "GradualNECheckSynthRdx"
  (GradualNECheck Gamma gu_^^ et_^^ gtSynth gU)]

;; #source file ./ott/lang_simple.ott  lines 2321 - 2328 

;; #source file ./ott/lang_simple.ott  lines 2329 - 2334 

;; #source file ./ott/lang_simple.ott  lines 2344 - 2352 
 [
  (ConsistentSet gU_^^)
  (GradualNECheck Gamma gU_11 eT_11 gT_11 gU_^^)
    
  (GradualNECheck (EnvExt x gU_11 Gamma) gU_22 eT_22 gT_22 gU_^^)
  -------------------------------------------------------------------------------------------------------- "GradualNECheckPi"
  (GradualNECheck Gamma (CanonicalPi x gU_11 gU_22) (TermPi x eT_11 eT_22) (TermPi x gT_11 gT_22) gU_^^)]

;; #source file ./ott/lang_simple.ott  lines 2353 - 2357 

;; #source file ./ott/lang_simple.ott  lines 2358 - 2363 
 [
  
   (where   z  ,(gensym)) 
    
  (GradualNECheck (EnvExt z gU_11 Gamma) gu et  (substitute  gt   x   z )   (substitute  gU_22   y   z ) )
  ------------------------------------------------------------------------------------------------------------ "GradualNECheckLamPiRdxAlpha"
  (GradualNECheck Gamma  (CanonicalLam z gu)   (TermLam z et)   (TermLam x gt)  (CanonicalPi y gU_11 gU_22))]

;; #source file ./ott/lang_simple.ott  lines 2364 - 2368 
 [
  
    
  (GradualNECheck (EnvExt x CanonicalDyn Gamma) gu et gt CanonicalDyn)
  --------------------------------------------------------------------------------------------- "GradualNECheckLamDyn"
  (GradualNECheck Gamma  (CanonicalLam x gu)   (TermLam x et)   (TermLam x gt)  CanonicalDyn)]

;; #source file ./ott/lang_simple.ott  lines 2369 - 2372 
 [
  (GradualSet Gamma gU)
  --------------------------------------------------------------------------------------- "GradualNECheckDyn"
  (GradualNECheck Gamma CanonicalDyn (TermEp (EvidenceEv Gamma gU) TermDyn) TermDyn gU)]
)
;; #source file ./ott/lang_simple.ott  lines 2380 - 2380 
#| 

;;; definitions 

(define-judgment-form
  L
  #:mode (EvType I I I)
  #:contract (EvType Gamma et gU)

;; #source file ./ott/lang_simple.ott  lines 2393 - 2397 
 [
    
  (GVarLook x gU Gamma)
  ------------------------------- "EvTypeVar"
  (EvType Gamma x gU)]

;; #source file ./ott/lang_simple.ott  lines 2401 - 2406 
 [
  
  (EvType Gamma et_11 gU)
  (EvType Gamma et_22  (error "TODO") )
  (EvCod et_22 gU gU_22)
  -------------------------------------------- "EvTypeApp"
  (EvType Gamma (TermApp et_11 et_22) gU_22)]

;; #source file ./ott/lang_simple.ott  lines 2412 - 2418 
 [
  
  (ConsistentSet gU)
  (GNCheck Gamma gU_^ eT_11 gU)
    
  (EvType (EnvExt x gU_^ Gamma) eT_22 gU)
  ------------------------------------------ "EvTypePi"
  (EvType Gamma (TermPi x eT_11 eT_22) gU)]

;; #source file ./ott/lang_simple.ott  lines 2419 - 2422 
 [
   (side-condition ,(> (term  i ) 0)) 
  ------------------------------------------------------------------------ "EvTypeSet"
  (EvType Gamma (TermSet i) (CanonicalAtomic  (AtomicSet (succ  i ) ) ))]

;; #source file ./ott/lang_simple.ott  lines 2424 - 2428 
 [
  
  (EvType Gamma et gU_^)
  (EvConsistent ep gU_^ gU)
  ---------------------------------- "EvTypeEv"
  (EvType Gamma (TermEp ep et) gU)]

;; #source file ./ott/lang_simple.ott  lines 2429 - 2433 
 [
  (EvType Gamma eT (CanonicalAtomic (AtomicSet i)))
   (side-condition ,(and (< 0 (term  i )) (< (term  i ) (term  j )))) 
  --------------------------------------------------- "EvTypeLevel"
  (EvType Gamma eT (CanonicalAtomic (AtomicSet j)))]

;; #source file ./ott/lang_simple.ott  lines 2438 - 2442 
 [
  
    
  (EvType (EnvExt x gU_11 Gamma) et gU_22)
  ------------------------------------------------------------- "EvTypeLamPi"
  (EvType Gamma  (TermLam x et)  (CanonicalPi x gU_11 gU_22))]

;; #source file ./ott/lang_simple.ott  lines 2444 - 2448 
 [
  
    
  (EvType (EnvExt x CanonicalDyn Gamma) et CanonicalDyn)
  ---------------------------------------------- "EvTypeLamDyn"
  (EvType Gamma  (TermLam x et)  CanonicalDyn)]

;; #source file ./ott/lang_simple.ott  lines 2449 - 2453 
 [
  (GradualSet Gamma gU)
  (EvConsistent ep gU gU)
  --------------------------------------- "EvTypeDyn"
  (EvType Gamma (TermEp ep TermDyn) gU)]
)
;; #source file ./ott/lang_simple.ott  lines 2456 - 2456 
|# 

;;; definitions 

(define-judgment-form
  L
  #:mode (SimpleStep I O)
  #:contract (SimpleStep t_11 t_22)

;; #source file ./ott/lang_simple.ott  lines 2470 - 2472 
 [
  ---------------------------------- "SimpleStepAnn"
  (SimpleStep  (TermAnn sv T)  sv)]

;; #source file ./ott/lang_simple.ott  lines 2473 - 2475 
 [
  
  ------------------------------------------------------------------- "SimpleStepApp"
  (SimpleStep (TermApp  (TermLam x t)  sv)  (esubst  t   x   sv ) )]

;; #source file ./ott/lang_simple.ott  lines 2477 - 2480 
 [
  
  (SimpleStep t_11 t_22)
  -------------------------------------------------------------- "SimpleStepContext"
  (SimpleStep  (in-hole  SC   t_11 )   (in-hole  SC   t_22 ) )]

)
(define-judgment-form L 
 
  #:mode (Step I O)
  #:contract (Step et_11 et_22)

;; #source file ./ott/lang_simple.ott  lines 2488 - 2491 
 [
  (Meet  (type-in-ev  ep_11 )   (type-in-ev  ep_22 )   (type-in-ev  ep_33 ) )
  ------------------------------------------------------------- "StepAscr"
  (Step (TermEp ep_11  (TermEp ep_22 rv) ) (TermEp ep_33 rv))]

;; #source file ./ott/lang_simple.ott  lines 2494 - 2498 
 [
   (side-condition ,(empty? (judgment-holds (Meet   (type-in-ev  ep_11 )     (type-in-ev  ep_22 )   ep_9999) ep_9999))) 
   (side-condition ,(error 'RuntimeError "Can't cast:\n    ~a\nto\n   ~a\nin term ~a" (printEvType (term  ep_11 )) (printEvType (term  ep_22 )) (pt (term  rv )) )) 
  ----------------------------------------------------- "StepAscrFail"
  (Step (TermEp ep_11  (TermEp ep_22 rv) ) TermError)]

;; #source file ./ott/lang_simple.ott  lines 2510 - 2515 
 [
  
    
    (Domain  (type-in-ev  ep_11 )   (type-in-ev  ep_11^ ) )   (Meet  (type-in-ev  ep_22 )   (type-in-ev  ep_11^ )   (type-in-ev  ep_33 ) )  
  (EvCod rv  (type-in-ev  ep_11 )   (type-in-ev  ep_44 ) )
  --------------------------------------------------------------------------------------------------------------------------------- "StepAppEv"
  (Step (TermApp  (TermEp ep_11  (TermLam x et) )   (TermEp ep_22 rv) ) (TermEp ep_44   (esubst  et   x   (TermEp ep_33 rv) )  ))]

;; #source file ./ott/lang_simple.ott  lines 2518 - 2523 
 [
  
  (Domain  (type-in-ev  ep_11 )   (type-in-ev  ep_22 ) )
  (EvCod rv  (type-in-ev  ep_11 )   (type-in-ev  ep_33 ) )
  ---------------------------------------------------------------------------------------------------------------- "StepAppEvRaw"
  (Step (TermApp  (TermEp ep_11  (TermLam x et) )  rv) (TermEp ep_33   (esubst  et   x   (TermEp ep_22 rv) )  ))]

;; #source file ./ott/lang_simple.ott  lines 2524 - 2526 
 [
  
  --------------------------------------------------------------- "StepApp"
  (Step (TermApp  (TermLam x et)  ev)  (esubst  et   x   ev ) )]

;; #source file ./ott/lang_simple.ott  lines 2527 - 2530 
 [
  (EvCod ev  (type-in-ev  ep_11 )   (type-in-ev  ep_22 ) )
  --------------------------------------------------------------------- "StepAppDyn"
  (Step (TermApp  (TermEp ep_11 TermDyn)  ev) (TermEp ep_22 TermDyn))]

;; #source file ./ott/lang_simple.ott  lines 2532 - 2537 
 [
  
  (Domain  (type-in-ev  ep_11 )   (type-in-ev  ep_33 ) )
   (side-condition ,(empty? (judgment-holds (Meet   (type-in-ev  ep_33 )     (type-in-ev  ep_22 )   ep_9999) ep_9999))) 
   (side-condition ,(error 'RuntimeError "Can't cast:\n    ~a\nto\n   ~a\nin term ~a" (printEvType (term  ep_33 )) (printEvType (term  ep_22 )) (pt (term   (TermApp rv_11 rv_22)  )) )) 
  -------------------------------------------------------------------------- "StepAppFailTrans"
  (Step (TermApp  (TermEp ep_11 rv_11)   (TermEp ep_22 rv_22) ) TermError)]

;; #source file ./ott/lang_simple.ott  lines 2543 - 2547 
 [
  
   (side-condition ,(empty? (judgment-holds (Domain   (type-in-ev  ep_11 )   gU_9999) gU_9999))) 
   (side-condition ,(error 'RuntimeError "Can't cast:\n    ~a\nto\n   ~a\nin term ~a" (printEvType (term  ep_11 )) (printEvType (term   (EvidenceEv EnvEmpty  (CanonicalPi x CanonicalDyn CanonicalDyn) )  )) (pt (term   (TermApp rv ev)  )) )) 
  --------------------------------------------------- "StepAppFailDom"
  (Step (TermApp  (TermEp ep_11 rv)  ev) TermError)]

;; #source file ./ott/lang_simple.ott  lines 2560 - 2564 

;; #source file ./ott/lang_simple.ott  lines 2565 - 2568 

)
(define-judgment-form L 
 
  #:mode (EvCod I I O)
  #:contract (EvCod et gU_11 gU_22)

;; #source file ./ott/lang_simple.ott  lines 2610 - 2615 
 [
    
    (Domain gU gU_^)   (GNCheck EnvEmpty gu et gU_^)  
  (CodSub gu gU gU_22)
  --------------------- "EvCodSub"
  (EvCod et gU gU_22)]
)
;; #source file ./ott/lang_simple.ott  lines 2631 - 2645 
(define-judgment-form
  L
  #:mode (ElabNormType I I O)
  [ (GradualNESynth Gamma gt et gu gU)
  ---------------------------------
  (ElabNormType Gamma gt (ENTTriple et gu gU))]

)

